#!/usr/bin/env node
/**
 * Assemble modular desktop/src/*.js → desktop/plugin.js
 *
 * Hermes disk plugins may ONLY import @hermes/plugin-sdk and react*.
 * Relative imports are rejected by the runtime loader, so we keep a modular
 * source tree for humans and concatenate into one shippable file.
 *
 * Usage (from plugin root or desktop/):
 *   node desktop/assemble.mjs
 *
 * Deploy on your Mac:
 *   cp desktop/plugin.js ~/.hermes/desktop-plugins/workstreamer/plugin.js
 *   then ⌘K → Reload desktop plugins
 *
 * NEVER write into a Hermes profile directory from this script.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SRC = path.join(__dirname, 'src')
const OUT = path.join(__dirname, 'plugin.js')

const ORDER = [
  'constants.js',
  'health.js',
  'format.js',
  'atoms.js',
  'chip.js',
  'map.js',
  'plugin.entry.js',
]

function stripModuleSyntax(code, filename) {
  let out = code
  out = out.replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '')
  out = out.replace(/^export\s+default\s+/gm, 'const __plugin_default = ')
  out = out.replace(/^export\s+(async\s+)?function\s+/gm, '$1function ')
  out = out.replace(/^export\s+const\s+/gm, 'const ')
  out = out.replace(/^export\s+\{[^}]+\}\s*;?\s*$/gm, '')
  return `\n/* ──── ${filename} ──── */\n${out.trim()}\n`
}

const sdkNames = new Set()
const reactRuntime = new Set()
const reactNames = new Set()

for (const file of ORDER) {
  const raw = fs.readFileSync(path.join(SRC, file), 'utf8')
  for (const m of raw.matchAll(/import\s+\{([^}]+)\}\s+from\s+['"]@hermes\/plugin-sdk['"]/g)) {
    m[1].split(',').forEach(s => {
      const name = s.trim().split(/\s+as\s+/).pop().trim()
      if (name) sdkNames.add(name)
    })
  }
  for (const m of raw.matchAll(/import\s+\{([^}]+)\}\s+from\s+['"]react\/jsx-runtime['"]/g)) {
    m[1].split(',').forEach(s => {
      const name = s.trim().split(/\s+as\s+/).pop().trim()
      if (name) reactRuntime.add(name)
    })
  }
  for (const m of raw.matchAll(/import\s+\{([^}]+)\}\s+from\s+['"]react['"]/g)) {
    m[1].split(',').forEach(s => {
      const name = s.trim().split(/\s+as\s+/).pop().trim()
      if (name) reactNames.add(name)
    })
  }
}

sdkNames.add('host') // format.js uses bare host after assemble

const header = `/**
 * workstreamer — Desktop UI (ASSEMBLED)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: desktop/src/*.js
 * Rebuild: node desktop/assemble.mjs
 *
 * Modules: constants, health, format, atoms, chip, map, entry
 *
 * Deploy (Mac):
 *   mkdir -p ~/.hermes/desktop-plugins/workstreamer
 *   cp desktop/plugin.js ~/.hermes/desktop-plugins/workstreamer/plugin.js
 *   ⌘K → Reload desktop plugins
 */
import {
  ${[...sdkNames].sort().join(',\n  ')}
} from '@hermes/plugin-sdk'
import { ${[...reactRuntime].sort().join(', ')} } from 'react/jsx-runtime'
import { ${[...reactNames].sort().join(', ')} } from 'react'
`

const body = ORDER.map(f =>
  stripModuleSyntax(fs.readFileSync(path.join(SRC, f), 'utf8'), f)
).join('\n')

const footer = `\nexport default __plugin_default\n`
const bundled = header + body + footer

fs.writeFileSync(OUT, bundled)

if (/from\s+['"]\.\//.test(bundled)) {
  console.error('ERROR: residual relative imports in bundle')
  process.exit(1)
}
if (/StatusDot,\s*\{\s*color\s*:/.test(bundled)) {
  console.error('ERROR: StatusDot still uses color= (must be tone=)')
  process.exit(1)
}

console.log(`assembled ${bundled.length} bytes → ${OUT}`)
console.log(`sdk imports: ${sdkNames.size}, react: ${reactNames.size}, jsx: ${reactRuntime.size}`)
console.log('Deploy on Mac only — this script never writes into Hermes profiles.')
