/**
 * workstreamer — Desktop UI (ASSEMBLED)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: desktop/src/*.js
 * Rebuild: node desktop/assemble.mjs
 *
 * Modules: constants, health, format, persist, lists, atoms, chip, map, entry
 *
 * Deploy (Mac):
 *   mkdir -p ~/.hermes/desktop-plugins/workstreamer
 *   cp desktop/plugin.js ~/.hermes/desktop-plugins/workstreamer/plugin.js
 *   ⌘K → Reload desktop plugins
 */
import {
  Badge,
  Button,
  EmptyState,
  ErrorState,
  Input,
  KEYBINDS_AREA,
  PALETTE_AREA,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ROUTES_AREA,
  SIDEBAR_NAV_AREA,
  STATUSBAR_AREAS,
  SearchField,
  SegmentedControl,
  Separator,
  Skeleton,
  StatusDot,
  Tip,
  cn,
  haptic,
  host,
  useQuery,
  useQueryClient,
  useValue
} from '@hermes/plugin-sdk'
import { jsx, jsxs } from 'react/jsx-runtime'
import { useEffect, useMemo, useState } from 'react'

/* ──── constants.js ──── */
/** @section constants */
const ID = 'workstreamer'

const FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'issues', label: 'Issues' },
  { id: 'adopted', label: 'Adopted' },
  { id: 'bare', label: 'Bare' },
]

const STORAGE_KEYS = {
  filter: 'map.filter',
  selected: 'map.selected',
  pinned: 'chip.pinned',
  view: 'chip.view',
  morningDate: 'chip.morningDate',
  pageTab: 'map.tab',
}


/* ──── health.js ──── */
/** @section health */
/** Map domain health → Hermes StatusDot tone (good|muted|warn|bad). */
function healthMeta(health) {
  const map = {
    clean: { tone: 'good', label: 'clean', short: 'clean', badge: 'default' },
    adopted: { tone: 'good', label: 'adopted', short: 'ok', badge: 'default' },
    active: { tone: 'warn', label: 'in motion', short: 'active', badge: 'warn' },
    degraded: { tone: 'bad', label: 'degraded', short: 'down', badge: 'destructive' },
    dirty: { tone: 'bad', label: 'dirty', short: 'dirty', badge: 'destructive' },
    stale: { tone: 'warn', label: 'stale status', short: 'stale', badge: 'warn' },
    partial: { tone: 'warn', label: 'partial', short: 'partial', badge: 'warn' },
    bare: { tone: 'muted', label: 'bare', short: 'bare', badge: 'muted' },
  }
  return map[health] || { tone: 'muted', label: health || '…', short: health || '…', badge: 'muted' }
}

function toneOf(t) {
  if (t === 'good' || t === 'clean' || t === 'adopted') return 'good'
  if (t === 'active' || t === 'partial' || t === 'warn' || t === 'stale') return 'warn'
  if (t === 'bad' || t === 'dirty' || t === 'degraded' || t === 'error') return 'bad'
  return 'muted'
}

function badgeVariantForTone(t) {
  const x = toneOf(t)
  if (x === 'good') return 'default'
  if (x === 'warn') return 'warn'
  if (x === 'bad') return 'destructive'
  return 'muted'
}


/* ──── format.js ──── */
/** @section format */

function extractStreamName(cwd) {
  if (!cwd) return null
  const m = String(cwd).match(/workstreams\/([^/]+)/)
  return m ? m[1] : null
}

function titleCase(name) {
  if (!name) return ''
  return String(name)
    .split(/[-_]/)
    .map(p => (p ? p.charAt(0).toUpperCase() + p.slice(1) : ''))
    .join(' ')
}

function isApiMissing(e) {
  const s = errMsg(e)
  return /No such API endpoint/i.test(s) || (/\/api\/plugins\/workstreamer\//i.test(s) && /404/.test(s))
}

function errMsg(e) {
  if (!e) return 'unknown error'
  let raw = ''
  if (typeof e === 'string') raw = e
  else if (e.detail && typeof e.detail === 'object') {
    raw = e.detail.error || e.detail.message || JSON.stringify(e.detail)
  } else {
    raw = e.message || e.detail || e.error || String(e)
  }

  if (/No such API endpoint/i.test(raw) || (/404/.test(raw) && /workstreamer/.test(raw))) {
    return 'API not mounted on this dashboard. Copy the Python plugin to the SAME Hermes host Desktop is connected to (dashboard/manifest.json + plugins.enabled + restart). plugin.js alone is only the UI.'
  }
  if (/unauthenticated|Unauthorized|no_cookie/i.test(raw)) {
    return 'Dashboard rejected the request (not logged in). Reconnect / log in to this dashboard.'
  }
  return raw
}

function ago(ts) {
  if (!ts) return ''
  const s = Math.max(0, Math.floor(Date.now() / 1000 - Number(ts)))
  if (s < 10) return 'just now'
  if (s < 60) return `${s}s ago`
  if (s < 3600) return `${Math.floor(s / 60)}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return `${Math.floor(s / 86400)}d ago`
}

function stripMd(s) {
  return String(s || '')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1')
    .replace(/[*_`]/g, '')
    .replace(/^\s*[-*•]+\s+/, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/** True only for a real PR bullet (#29 or github.com/…/pull/29).
 *  STATUS-LIVE preamble ("Last updated", "DO NOT TRUST") must never render. */
function isPrLine(raw) {
  const text = stripMd(raw)
  if (!text) return false
  if (/last updated/i.test(text)) return false
  if (/do not trust/i.test(text)) return false
  return /#\d+/.test(text) || /github\.com\/.+\/pull\/\d+/i.test(text)
}

/** Turn a STATUS-LIVE PR bullet into { number, title, extra, url }.
 *  `repo` comes from the snapshot (git remote / AGENTS.md) — never a plugin table. */
function parsePr(raw, repo) {
  const source = String(raw || '')
  const urlMatch = source.match(/\((https?:\/\/[^)\s]+)\)/)
  const text = stripMd(source)
  const numMatch = text.match(/#(\d+)/)
  let rest = text.replace(/#\d+\b\s*/, '').trim()
  let extra = ''
  const paren = rest.match(/^(.*?)\s*\(([^)]+)\)\s*$/)
  if (paren) {
    rest = paren[1].trim()
    extra = paren[2].trim()
  }
  const number = numMatch ? numMatch[1] : ''
  const base = String(repo || '').replace(/\/+$/, '')
  const url = urlMatch ? urlMatch[1] : number && base ? `${base}/pull/${number}` : ''
  return {
    number,
    title: rest || text || 'PR',
    extra,
    url,
    raw: text,
    valid: isPrLine(source),
  }
}

/** Expand a STATUS-LIVE host cell. Pattern, not a registry:
 *  already-https stays; `fe.sq` / `bk.sq.dabbo.net` → https://… */
function hrefForUrl(name) {
  const n = String(name || '').trim()
  if (!n) return ''
  if (/^https?:\/\//i.test(n)) return n
  if (/^[a-z0-9-]+\.[a-z0-9-]+$/i.test(n) && !n.includes('/')) {
    return `https://${n}.dabbo.net`
  }
  if (/^[a-z0-9.-]+\.[a-z]{2,}(\/|$)/i.test(n)) return `https://${n}`
  return ''
}

async function copyText(text) {
  const t = String(text || '')
  if (!t) return false
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(t)
      return true
    }
  } catch {
    /* fall through */
  }
  try {
    if (typeof host.copy === 'function') {
      await host.copy(t)
      return true
    }
  } catch {
    /* ignore */
  }
  return false
}

function openHref(href) {
  if (!href) return
  try {
    if (typeof host.open === 'function') {
      host.open(href)
      return
    }
    if (typeof host.openExternal === 'function') {
      host.openExternal(href)
      return
    }
  } catch {
    /* fall through */
  }
  try {
    window.open(href, '_blank', 'noopener,noreferrer')
  } catch {
    /* ignore */
  }
}

function hostCwd() {
  try {
    const a = host.state.cwd
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}

function hostProfile() {
  try {
    const a = host.state.profile
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}


/* ──── persist.js ──── */
/** @section persist */

function usePersisted(ctx, key, fallback) {
  const [value, setValue] = useState(fallback)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const v = await ctx.storage.get(key)
        if (!cancelled && v != null && v !== '') setValue(v)
      } catch {
        /* ignore */
      }
    })()
    return () => {
      cancelled = true
    }
  }, [ctx, key])

  const set = (next) => {
    setValue(next)
    try {
      void ctx.storage.set(key, next)
    } catch {
      /* ignore */
    }
  }

  return [value, set]
}


/* ──── lists.js ──── */
/** @section lists — pulse.json helpers (chip + page share these) */

const MISSION_STATUSES = ['todo', 'doing', 'blocked', 'later', 'done', 'cancelled']

function listsOf(data) {
  return data?.lists || null
}

function hasLists(data) {
  const lists = listsOf(data)
  return Boolean(lists?.ok && lists?.pulse && Array.isArray(lists.pulse.missions))
}

function listsInvalid(data) {
  const lists = listsOf(data)
  return Boolean(lists && lists.ok === false && lists.source === 'invalid')
}

function listsEmpty(data) {
  const lists = listsOf(data)
  return Boolean(lists?.ok && lists.source === 'empty')
}

function pulseOf(data) {
  return hasLists(data) ? data.lists.pulse : null
}

function viewOf(data) {
  return hasLists(data) ? data.lists.view || {} : {}
}

function sortedMissions(pulse) {
  const items = Array.isArray(pulse?.missions) ? pulse.missions.slice() : []
  return items.sort((a, b) => {
    const ao = Number(a.order)
    const bo = Number(b.order)
    const an = Number.isFinite(ao) ? ao : 0
    const bn = Number.isFinite(bo) ? bo : 0
    if (an !== bn) return an - bn
    return String(a.id || '').localeCompare(String(b.id || ''))
  })
}

function openMissions(pulse) {
  return sortedMissions(pulse).filter(m => m.status !== 'done' && m.status !== 'cancelled')
}

function nextMission(data) {
  const v = viewOf(data)
  if (v.next_mission) return v.next_mission
  const pulse = pulseOf(data)
  return openMissions(pulse)[0] || null
}

function openBlockers(pulse) {
  return (pulse?.blockers || []).filter(b => b.status !== 'resolved')
}

function waitingOn(pulse) {
  return openBlockers(pulse).filter(b => b.kind === 'waiting-on')
}

function stuckOn(pulse) {
  return openBlockers(pulse).filter(b => b.kind === 'stuck-on')
}

function blockerById(pulse, id) {
  if (!id) return null
  return (pulse?.blockers || []).find(b => b.id === id) || null
}

function resourceById(pulse, id) {
  if (!id) return null
  return (pulse?.resources || []).find(r => r.id === id) || null
}

function todayISO(tz) {
  try {
    const fmt = new Intl.DateTimeFormat('en-CA', {
      timeZone: tz || 'Africa/Cairo',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    })
    return fmt.format(new Date())
  } catch {
    return new Date().toISOString().slice(0, 10)
  }
}

/** Overdue first, then pins, then pile. Cap 3. */
function recommendToday(pulse, tz) {
  const date = todayISO(tz || pulse?.timezone)
  const open = openMissions(pulse)
  const pins = pulse?.today?.pinned_mission_ids || []
  const byId = Object.fromEntries(open.map(m => [m.id, m]))
  const rank = (m) => {
    const overdue = m.due && String(m.due) <= date ? 0 : 1
    const order = Number.isFinite(Number(m.order)) ? Number(m.order) : 0
    return [overdue, order, String(m.id || '')]
  }
  const ranked = open.slice().sort((a, b) => {
    const aa = rank(a)
    const bb = rank(b)
    for (let i = 0; i < aa.length; i++) {
      if (aa[i] < bb[i]) return -1
      if (aa[i] > bb[i]) return 1
    }
    return 0
  })
  const out = []
  const seen = new Set()
  // 1. overdue first
  for (const m of ranked) {
    if (m.due && String(m.due) <= date && m.id && !seen.has(m.id)) {
      seen.add(m.id)
      out.push(m)
    }
    if (out.length >= 3) return out.slice(0, 3)
  }
  // 2. last night's pins
  for (const id of pins) {
    if (byId[id] && !seen.has(id)) {
      seen.add(id)
      out.push(byId[id])
    }
    if (out.length >= 3) return out.slice(0, 3)
  }
  // 3. rest of the pile
  for (const m of ranked) {
    if (m.id && !seen.has(m.id)) {
      seen.add(m.id)
      out.push(m)
    }
    if (out.length >= 3) break
  }
  return out.slice(0, 3)
}

function isOverdue(m, date) {
  return Boolean(m?.due && date && String(m.due) < date)
}

function statusTone(status) {
  if (status === 'doing') return 'warn'
  if (status === 'blocked') return 'bad'
  if (status === 'done') return 'good'
  if (status === 'cancelled' || status === 'later') return 'muted'
  return 'muted'
}

function modeLabel(mode) {
  if (mode === 'quiet') return 'quiet'
  if (mode === 'hunt') return 'hunt'
  return 'steer'
}

async function patchLists(ctx, stream, op) {
  const q = `?stream=${encodeURIComponent(stream)}`
  return ctx.rest(`/stream${q}`, { method: 'PATCH', body: op })
}


/* ──── atoms.js ──── */
/** @section atoms */




function Muted({ children, className }) {
  return jsx('span', {
    className: cn('text-[10px] leading-tight', className),
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function SectionLabel({ children }) {
  return jsx('div', {
    className: 'text-[10px] uppercase tracking-wide font-medium',
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function ProgressBar({ pct, tone }) {
  const p = Math.max(0, Math.min(100, Number(pct) || 0))
  const t = toneOf(tone)
  const color =
    t === 'good' ? 'var(--ui-green, var(--primary))'
      : t === 'bad' ? 'var(--destructive)'
        : t === 'warn' ? 'rgb(245 158 11)'
          : 'var(--muted-foreground)'
  return jsx('div', {
    className: 'h-1 w-full rounded-full overflow-hidden',
    style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
    role: 'progressbar',
    'aria-valuenow': p,
    'aria-valuemin': 0,
    'aria-valuemax': 100,
    children: jsx('div', {
      className: 'h-full rounded-full transition-[width] duration-200 ease-out',
      style: { width: `${p}%`, background: color },
    }),
  })
}

function MilestoneRail({ chips }) {
  if (!chips?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: chips.map(c =>
      jsx(Tip, {
        key: c.id,
        label: `${c.id}${c.label ? ` · ${c.label}` : ''}${c.status ? ` — ${c.status}` : ''}`,
        children: jsxs('div', {
          className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
          style: {
            background: 'var(--ui-stroke-secondary, var(--muted))',
            color: 'var(--ui-text-secondary, var(--muted-foreground))',
          },
          children: [
            jsx(StatusDot, { tone: toneOf(c.tone) }),
            jsx('span', { className: 'font-medium', children: c.id }),
            c.pct != null
              ? jsx('span', {
                  style: { color: 'var(--ui-text-quaternary)' },
                  children: `${c.pct}%`,
                })
              : null,
          ],
        }),
      })
    ),
  })
}

function UrlPills({ urls }) {
  if (!urls?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: urls.map(u => {
      const href = hrefForUrl(u.name)
      const tone = toneOf(u.tone)
      const body = jsxs(href ? 'button' : 'div', {
        type: href ? 'button' : undefined,
        className: cn(
          'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px]',
          href && 'hover:opacity-80 cursor-pointer'
        ),
        style: {
          background: 'var(--ui-stroke-secondary, var(--muted))',
          color: tone === 'bad'
            ? 'var(--destructive)'
            : 'var(--ui-text-secondary, var(--muted-foreground))',
        },
        onClick: href
          ? (e) => {
              e.stopPropagation()
              haptic('tap')
              openHref(href)
            }
          : undefined,
        children: [
          jsx(StatusDot, { tone }),
          u.name,
        ],
      })
      return jsx(Tip, {
        key: u.name,
        label: href ? `${u.status || u.name} · open` : String(u.status || u.name),
        children: body,
      })
    }),
  })
}

function CoreChecklist({ core }) {
  if (!core) return null
  const missing = [...(core.missing || [])]
  if (!core.has_checker) missing.push('scripts/check-workstream.sh')
  if (!core.has_status) missing.push('scope/STATUS-LIVE.md')

  if (!missing.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        `Core complete · ${core.pct}%`,
      ],
    })
  }

  return jsxs('div', {
    className: 'flex flex-col gap-1',
    children: [
      jsxs('div', {
        className: 'flex items-center justify-between text-xs',
        children: [
          jsx('span', {
            style: { color: 'var(--ui-text-secondary)' },
            children: 'Constitution',
          }),
          jsx(Muted, { children: `${core.score}/${core.total}` }),
        ],
      }),
      jsx(ProgressBar, {
        pct: core.pct,
        tone: core.pct === 100 ? 'good' : 'warn',
      }),
      jsx('div', {
        className: 'flex flex-col gap-0.5 mt-0.5',
        children: missing.slice(0, 5).map(f =>
          jsxs('div', {
            key: f,
            className: 'flex items-center gap-1.5 text-[10px]',
            style: { color: 'var(--ui-text-quaternary)' },
            children: [
              jsx('span', { children: '○' }),
              f,
            ],
          })
        ),
      }),
    ],
  })
}

function BlockerList({ blockers }) {
  if (!blockers?.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [jsx(StatusDot, { tone: 'good' }), 'No blockers listed'],
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: blockers.slice(0, 6).map((b, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs leading-snug',
        children: [
          jsx('span', {
            className: 'shrink-0 mt-0.5',
            style: { color: 'var(--destructive)' },
            children: '▸',
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: b,
          }),
        ],
      })
    ),
  })
}

function PrList({ prs, compact = false, limit = 6, repo }) {
  const items = (prs || [])
    .filter(isPrLine)
    .slice(0, limit)
    .map(raw => parsePr(raw, repo))
    .filter(pr => pr.valid)
  if (!items.length) return null
  return jsx('div', {
    className: 'flex flex-col',
    children: items.map((pr, i) => {
      const row = jsxs(pr.url ? 'button' : 'div', {
        type: pr.url ? 'button' : undefined,
        key: `${pr.number || pr.title}-${i}`,
        className: cn(
          'flex items-start gap-2 text-xs text-left w-full',
          compact ? 'py-0.5' : 'py-1.5',
          i > 0 && !compact ? 'border-t' : '',
          pr.url && 'hover:opacity-80 cursor-pointer'
        ),
        style: i > 0 && !compact
          ? { borderColor: 'var(--ui-stroke-secondary, var(--border))' }
          : undefined,
        onClick: pr.url
          ? (e) => {
              e.stopPropagation()
              haptic('tap')
              openHref(pr.url)
            }
          : undefined,
        children: [
          pr.number
            ? jsx(Badge, {
                variant: 'muted',
                size: 'xs',
                className: 'shrink-0 font-mono tabular-nums',
                children: `#${pr.number}`,
              })
            : jsx(StatusDot, { tone: 'muted' }),
          jsxs('div', {
            className: 'min-w-0 flex-1 flex flex-col gap-0.5',
            children: [
              jsx('span', {
                className: compact ? 'truncate' : 'leading-snug',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: pr.title,
              }),
              pr.extra
                ? jsx(Muted, { children: pr.extra })
                : null,
            ],
          }),
        ],
      })
      return pr.url
        ? jsx(Tip, { key: `${pr.number || pr.title}-${i}`, label: 'Open PR', children: row })
        : row
    }),
  })
}

function ViolationList({ check }) {
  if (!check) return null
  if (check.status === 'no_script') {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: 'No check-workstream.sh — adopt or add scripts/',
    })
  }
  if (check.status === 'clean') {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        check.summary_line || 'Clean — no violations',
      ],
    })
  }
  const items = [
    ...(check.violations || []).map(v => ({ ...v, kind: 'v' })),
    ...(check.warnings || []).map(v => ({ ...v, kind: 'w' })),
  ]
  if (!items.length) {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: check.summary_line || check.status,
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: items.slice(0, 8).map((it, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs',
        children: [
          jsx('span', {
            className: 'font-mono text-[10px] shrink-0',
            style: {
              color: it.kind === 'v' ? 'var(--destructive)' : 'rgb(245 158 11)',
            },
            children: it.rule || (it.kind === 'v' ? 'R?' : 'W'),
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: it.message,
          }),
        ],
      })
    ),
  })
}

function StatChip({ label, value, tone }) {
  return jsxs('div', {
    className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
    style: {
      background: 'var(--ui-stroke-secondary, var(--muted))',
      color: 'var(--ui-text-secondary, var(--muted-foreground))',
    },
    children: [
      tone ? jsx(StatusDot, { tone: toneOf(tone) }) : null,
      jsx('span', { className: 'font-semibold', children: value }),
      jsx('span', {
        style: { color: 'var(--ui-text-quaternary)' },
        children: label,
      }),
    ],
  })
}

function HealthBadge({ health }) {
  const hm = healthMeta(health)
  return jsx(Badge, {
    variant: hm.badge,
    size: 'xs',
    children: hm.label,
  })
}

function RecheckButton({ onClick, busy, size = 'sm' }) {
  return jsx(Button, {
    size,
    variant: 'secondary',
    disabled: busy,
    onClick,
    children: busy ? '…' : 'Recheck',
  })
}

function DetailCard({ title, children, className }) {
  return jsxs('section', {
    className: cn(
      'rounded-md border p-3 flex flex-col gap-2 min-w-0',
      className
    ),
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      title ? jsx(SectionLabel, { children: title }) : null,
      children,
    ],
  })
}


/* ──── chip.js ──── */
/** @section chip */









function chipTitle(streamName, data) {
  return data?.title || titleCase(streamName) || streamName
}

const FLIP_CYCLE = ['todo', 'doing', 'later', 'done']

function WorkstreamChip({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const profile = useValue(host.state.profile)
  const streamFromCwd = extractStreamName(cwd)
  const [open, setOpen] = useState(false)
  const [switching, setSwitching] = useState(false)
  const [pinned, setPinned] = usePersisted(ctx, STORAGE_KEYS.pinned, '')
  const [view, setView] = usePersisted(ctx, STORAGE_KEYS.view, 'glance')
  const [morningDate, setMorningDate] = usePersisted(ctx, STORAGE_KEYS.morningDate, '')
  const qc = useQueryClient()

  const { data: resolved } = useQuery({
    queryKey: [ID, 'resolve', streamFromCwd || '', profile || ''],
    queryFn: async () => {
      if (streamFromCwd) return { stream: streamFromCwd, source: 'cwd' }
      const q = new URLSearchParams()
      if (profile) q.set('profile', String(profile))
      if (cwd) q.set('cwd', String(cwd))
      return ctx.rest(`/resolve?${q}`)
    },
    refetchInterval: 30_000,
    retry: 1,
  })

  const liveName = resolved?.stream || streamFromCwd || ''
  const streamName = pinned || liveName

  const { data: fleet } = useQuery({
    queryKey: [ID, 'list'],
    queryFn: () => ctx.rest('/list?pulse=true&check=false'),
    refetchInterval: 60_000,
    retry: 1,
    enabled: open,
  })

  const { data, isFetching, isError, error, refetch } = useQuery({
    queryKey: [ID, 'stream', streamName || 'none'],
    queryFn: async () => {
      if (!streamName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(streamName)}&check=true`
      )
    },
    enabled: Boolean(streamName),
    refetchInterval: 45_000,
    retry: 1,
  })

  if (!streamName) {
    return jsx(Tip, {
      label: 'No workstream — open page',
      children: jsxs('button', {
        type: 'button',
        className:
          'inline-flex h-full items-center gap-1 rounded-none px-1.5 text-[0.6875rem] transition-colors hover:bg-(--chrome-action-hover)',
        style: { color: 'var(--ui-text-quaternary)' },
        onClick: () => {
          haptic('tap')
          host.navigate('/workstream-map')
        },
        children: [
          jsx(StatusDot, { tone: 'muted' }),
          'no stream',
        ],
      }),
    })
  }

  const hm = healthMeta(data?.health)
  const pulse = pulseOf(data)
  const nxt = nextMission(data)
  const waitN = pulse ? waitingOn(pulse).length : (data?.waiting_on_count || 0)
  const title = chipTitle(streamName, data)
  const tipBits = [
    title,
    pinned && pinned !== liveName ? `pinned (cwd: ${liveName || '—'})` : null,
    nxt ? `Next: ${nxt.title}` : data?.focus_label,
    waitN ? `${waitN} waiting-on` : null,
    isError ? `Error: ${errMsg(error)}` : null,
  ].filter(Boolean)

  return jsx(Popover, {
    open,
    onOpenChange: (v) => {
      setOpen(v)
      if (!v) setSwitching(false)
    },
    children: [
      jsx(PopoverTrigger, {
        key: 'trigger',
        children: jsxs('button', {
          type: 'button',
          title: tipBits.join(' · ') || streamName,
          className: cn(
            'inline-flex h-full max-w-[300px] items-center gap-1.5 rounded-none px-1.5',
            'text-[0.6875rem] tabular-nums transition-colors',
            'hover:bg-(--chrome-action-hover)',
            isFetching && !data && 'opacity-70'
          ),
          style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
          children: [
            jsx(StatusDot, { tone: isError ? 'bad' : hm.tone }),
            jsx('span', { className: 'truncate font-medium', children: title }),
            nxt
              ? jsx('span', {
                  className: 'hidden sm:inline truncate max-w-[120px]',
                  style: { color: 'var(--ui-text-quaternary)' },
                  children: nxt.title,
                })
              : null,
            waitN
              ? jsx('span', {
                  className: 'hidden sm:inline tabular-nums shrink-0',
                  style: { color: 'var(--destructive)' },
                  children: waitN,
                })
              : null,
            pinned
              ? jsx('span', {
                  className: 'text-[9px] opacity-50 shrink-0',
                  children: '●',
                })
              : null,
          ],
        }),
      }),
      jsx(PopoverContent, {
        key: 'content',
        className: 'w-[26rem] max-h-[min(80vh,640px)] overflow-y-auto p-0',
        align: 'end',
        children: jsx(StreamPopover, {
          ctx,
          streamName,
          liveName,
          pinned,
          setPinned,
          switching,
          setSwitching,
          view,
          setView,
          morningDate,
          setMorningDate,
          fleet: fleet?.streams || [],
          data,
          isError,
          error,
          isFetching,
          onClose: () => {
            setOpen(false)
            setSwitching(false)
          },
          onRefresh: async () => {
            haptic('tap')
            try {
              await ctx.rest(
                `/stream?stream=${encodeURIComponent(streamName)}&check=true&force=true`
              )
            } catch {
              /* refetch below surfaces error */
            }
            await refetch()
            qc.invalidateQueries({ queryKey: [ID, 'list'] })
            qc.invalidateQueries({ queryKey: [ID, 'stream'] })
          },
          onMutated: async () => {
            await refetch()
            qc.invalidateQueries({ queryKey: [ID, 'list'] })
            qc.invalidateQueries({ queryKey: [ID, 'stream'] })
          },
        }),
      }),
    ],
  })
}

function Count({ n, label, tone }) {
  if (!n) return null
  return jsxs('span', {
    className: 'inline-flex items-center gap-1 text-[10px] tabular-nums',
    style: {
      color:
        tone === 'bad'
          ? 'var(--destructive)'
          : tone === 'warn'
            ? 'rgb(245 158 11)'
            : 'var(--ui-text-quaternary)',
    },
    children: [
      jsx('span', { className: 'font-semibold', children: n }),
      label,
    ],
  })
}

function StreamSwitcher({ fleet, streamName, liveName, onPick }) {
  if (!fleet.length) {
    return jsx(Muted, { className: 'px-3.5 py-2', children: 'Loading fleet…' })
  }
  return jsx('div', {
    className: 'max-h-44 overflow-y-auto border-b',
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: fleet.map(s => {
      const isCur = s.name === streamName
      const isLive = s.name === liveName
      const hm = healthMeta(s.health)
      return jsxs('button', {
        key: s.name,
        type: 'button',
        className: cn(
          'w-full text-left px-3.5 py-1.5 flex items-center gap-2 text-xs',
          'hover:bg-accent/10',
          isCur && 'bg-accent/10'
        ),
        onClick: () => {
          haptic('tap')
          onPick(s.name)
        },
        children: [
          jsx(StatusDot, { tone: hm.tone }),
          jsx('span', { className: 'flex-1 truncate font-medium', children: s.title || s.name }),
          isLive ? jsx(Muted, { children: 'cwd' }) : null,
          isCur ? jsx(Muted, { children: 'now' }) : null,
        ],
      })
    }),
  })
}

function StreamPopover({
  ctx,
  streamName,
  liveName,
  pinned,
  setPinned,
  switching,
  setSwitching,
  view,
  setView,
  morningDate,
  setMorningDate,
  fleet,
  data,
  isError,
  error,
  isFetching,
  onClose,
  onRefresh,
  onMutated,
}) {
  const pulse = pulseOf(data)
  const check = data?.check
  const hm = healthMeta(data?.health)
  const title = chipTitle(streamName, data)
  const nxt = nextMission(data)
  const waitN = pulse ? waitingOn(pulse).length : 0
  const viol = check?.violation_count || 0
  const dirty = check?.status === 'dirty' || check?.status === 'no_script' || viol > 0 || listsInvalid(data)
  const isPinned = pinned === streamName
  const tz = pulse?.timezone || 'Africa/Cairo'
  const today = todayISO(tz)
  const showMorning = Boolean(openMissions(pulse).length) && morningDate !== today && hasLists(data)

  if (isError && !data) {
    const msg = errMsg(error)
    const auth = /unauthenticated|Unauthorized|no_cookie|not logged in/i.test(msg)
    const missing = /not mounted|No such API|404/i.test(msg)
    return jsxs('div', {
      className: 'p-3 flex flex-col gap-2',
      children: [
        jsx('div', {
          className: 'text-xs font-semibold',
          style: { color: 'var(--destructive)' },
          children: auth
            ? 'Dashboard auth required'
            : missing
              ? 'Plugin API missing on this dashboard'
              : 'Failed to load stream',
        }),
        jsx('div', {
          className: 'text-xs break-words',
          style: { color: 'var(--ui-text-secondary)' },
          children: msg,
        }),
        jsxs('div', {
          className: 'flex gap-1.5',
          children: [
            jsx(Button, {
              size: 'sm',
              variant: 'secondary',
              onClick: onRefresh,
              children: 'Retry',
            }),
            jsx(Button, {
              size: 'sm',
              variant: 'ghost',
              onClick: onClose,
              children: 'Close',
            }),
          ],
        }),
      ],
    })
  }

  const tab = view === 'jobs' ? 'jobs' : 'glance'

  return jsxs('div', {
    className: 'flex flex-col',
    children: [
      jsxs('div', {
        className: 'px-3.5 pt-3 pb-2 flex flex-col gap-2',
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsxs('button', {
                type: 'button',
                className: 'flex items-center gap-2 min-w-0 text-left hover:opacity-80',
                onClick: () => {
                  haptic('tap')
                  setSwitching(!switching)
                },
                children: [
                  jsx(StatusDot, { tone: hm.tone }),
                  jsx('span', {
                    className: 'font-semibold text-sm truncate',
                    children: title,
                  }),
                  jsx(Muted, { children: switching ? '▲' : '▼' }),
                ],
              }),
              jsxs('div', {
                className: 'flex items-center gap-1 shrink-0',
                children: [
                  pulse?.mode
                    ? jsx(Badge, { variant: 'muted', size: 'xs', children: pulse.mode })
                    : null,
                  data?.profile
                    ? jsx(Badge, { variant: 'muted', size: 'xs', children: `@${data.profile}` })
                    : null,
                  jsx(HealthBadge, { health: data?.health }),
                ],
              }),
            ],
          }),

          jsxs('div', {
            className: 'flex items-center gap-1',
            children: [
              jsx(Button, {
                size: 'xs',
                variant: tab === 'glance' ? 'secondary' : 'ghost',
                onClick: () => {
                  haptic('tap')
                  setView('glance')
                },
                children: 'Glance',
              }),
              jsx(Button, {
                size: 'xs',
                variant: tab === 'jobs' ? 'secondary' : 'ghost',
                disabled: listsInvalid(data),
                onClick: () => {
                  haptic('tap')
                  setView('jobs')
                },
                children: 'Jobs',
              }),
            ],
          }),

          jsxs('div', {
            className: 'flex items-center gap-2.5 flex-wrap',
            children: [
              jsx(Count, { n: waitN, label: 'waiting-on', tone: waitN ? 'bad' : null }),
              jsx(Count, {
                n: data?.blocker_count,
                label: 'blockers',
                tone: data?.blocker_count ? 'warn' : null,
              }),
              pulse?.updated_at
                ? jsx(Muted, { children: pulse.updated_at.slice(0, 10) })
                : data?.pulse?.updated
                  ? jsx(Muted, { children: data.pulse.updated })
                  : check?.checked_at
                    ? jsx(Muted, { children: ago(check.checked_at) })
                    : null,
            ],
          }),
        ],
      }),

      switching
        ? jsx(StreamSwitcher, {
            fleet,
            streamName,
            liveName,
            onPick: (name) => {
              setPinned(name)
              setSwitching(false)
            },
          })
        : null,

      listsInvalid(data)
        ? jsx(FailClosedBanner, { error: data?.lists?.error })
        : null,

      showMorning && tab === 'glance'
        ? jsx(MorningRec, {
            ctx,
            streamName,
            pulse,
            today,
            onDone: (d) => setMorningDate(d || today),
            onMutated,
          })
        : null,

      tab === 'jobs'
        ? jsx(JobsPane, {
            ctx,
            streamName,
            data,
            pulse,
            today,
            onMutated,
          })
        : jsx(GlancePane, {
            data,
            pulse,
            nxt,
            dirty,
            check,
          }),

      jsx(Separator, {}),

      jsxs('div', {
        className: 'flex gap-1.5 p-2',
        children: [
          jsx(Button, {
            size: 'sm',
            variant: 'secondary',
            disabled: isFetching,
            onClick: onRefresh,
            children: isFetching ? 'Checking…' : 'Recheck',
          }),
          jsx(Button, {
            size: 'sm',
            variant: isPinned ? 'secondary' : 'ghost',
            onClick: () => {
              haptic('tap')
              setPinned(isPinned ? '' : streamName)
            },
            children: isPinned ? 'Unpin' : 'Pin',
          }),
          jsx(Button, {
            size: 'sm',
            className: 'flex-1',
            onClick: () => {
              haptic('tap')
              onClose()
              host.navigate('/workstream-map')
            },
            children: 'Open page',
          }),
        ],
      }),
    ],
  })
}

function FailClosedBanner({ error }) {
  return jsxs('div', {
    className: 'mx-3.5 mb-2 rounded-[4px] px-2.5 py-2 flex flex-col gap-0.5',
    style: { background: 'color-mix(in oklab, var(--destructive) 12%, transparent)' },
    children: [
      jsx('div', {
        className: 'text-[11px] font-semibold',
        style: { color: 'var(--destructive)' },
        children: 'pulse.json invalid — not overwritten',
      }),
      jsx(Muted, { children: error || 'Fix the file by hand. Jobs disabled.' }),
    ],
  })
}

function GlancePane({ data, pulse, nxt, dirty, check }) {
  const nextTitle = nxt?.title || data?.pulse?.next_action || data?.focus_label || ''
  return jsxs('div', {
    className: 'px-3.5 pb-2.5 flex flex-col gap-2',
    children: [
      nextTitle
        ? jsxs('div', {
            className: 'rounded-[4px] px-2.5 py-2 flex flex-col gap-1',
            style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
            children: [
              jsxs('div', {
                className: 'flex items-center justify-between gap-2',
                children: [
                  jsx(SectionLabel, { children: 'Next' }),
                  jsx('button', {
                    type: 'button',
                    className: 'text-[10px]',
                    style: { color: 'var(--ui-text-quaternary)' },
                    onClick: async () => {
                      haptic('tap')
                      const ok = await copyText(nextTitle)
                      host.notify({
                        kind: ok ? 'success' : 'error',
                        message: ok ? 'Copied next mission' : 'Copy failed',
                      })
                    },
                    children: 'Copy',
                  }),
                ],
              }),
              jsx('div', {
                className: 'text-xs leading-snug font-medium',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: nextTitle,
              }),
              nxt?.status
                ? jsx(Muted, { children: nxt.status })
                : null,
            ],
          })
        : jsx(Muted, { children: hasLists(data) ? 'Pile is empty.' : 'No pulse yet — Jobs after first write.' }),
      dirty
        ? jsxs('div', {
            className: 'flex flex-col gap-1',
            children: [
              jsx(SectionLabel, { children: 'Checks' }),
              listsInvalid(data)
                ? jsx(Muted, { children: 'pulse.json invalid' })
                : jsx(ViolationList, { check }),
            ],
          })
        : null,
      !pulse && data?.pulse?.urls?.length
        ? jsx(Muted, { children: 'Glance from STATUS-LIVE — lists not mounted yet.' })
        : null,
    ],
  })
}

function MorningRec({ ctx, streamName, pulse, today, onDone, onMutated }) {
  const rec = recommendToday(pulse, pulse?.timezone)
  const [busy, setBusy] = useState(false)
  if (!rec.length) return null

  const pinToday = async (id, { swap } = {}) => {
    setBusy(true)
    haptic('tap')
    try {
      if (swap) {
        const open = (pulse?.missions || []).filter(m => m.status !== 'done' && m.status !== 'cancelled')
        const ids = [id, ...open.map(m => m.id).filter(x => x !== id)]
        await patchLists(ctx, streamName, { op: 'reorder', collection: 'missions', ids })
      }
      await patchLists(ctx, streamName, {
        op: 'patch_meta',
        meta: { today: { date: today, pinned_mission_ids: [id], accepted: true } },
      })
      onDone(today)
      await onMutated()
    } catch (e) {
      host.notify({ kind: 'error', message: errMsg(e) })
    } finally {
      setBusy(false)
    }
  }

  return jsxs('div', {
    className: 'mx-3.5 mb-2 rounded-[4px] border px-2.5 py-2 flex flex-col gap-1.5',
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      jsxs('div', {
        className: 'flex items-center justify-between',
        children: [
          jsx(SectionLabel, { children: 'Today?' }),
          jsx('button', {
            type: 'button',
            className: 'text-[10px]',
            style: { color: 'var(--ui-text-quaternary)' },
            disabled: busy,
            onClick: () => {
              haptic('tap')
              onDone(today)
            },
            children: 'Skip',
          }),
        ],
      }),
      rec.map(m =>
        jsxs('div', {
          key: m.id,
          className: 'flex items-center gap-2 text-xs',
          children: [
            jsx(StatusDot, { tone: statusTone(m.status) }),
            jsx('span', { className: 'flex-1 truncate', children: m.title }),
            m.due ? jsx(Muted, { children: m.due }) : null,
            jsx(Button, {
              size: 'xs',
              variant: 'ghost',
              disabled: busy,
              onClick: () => pinToday(m.id),
              children: 'Accept',
            }),
            jsx(Button, {
              size: 'xs',
              variant: 'ghost',
              disabled: busy,
              onClick: () => pinToday(m.id, { swap: true }),
              children: 'Swap',
            }),
          ],
        })
      ),
    ],
  })
}

function JobsPane({ ctx, streamName, data, pulse, today, onMutated }) {
  const [draft, setDraft] = useState('')
  const [noteLine, setNoteLine] = useState('')
  const [busy, setBusy] = useState(false)
  const [dragId, setDragId] = useState('')

  if (listsInvalid(data)) {
    return jsx('div', {
      className: 'px-3.5 pb-2',
      children: jsx(Muted, { children: 'Jobs disabled until pulse.json is valid.' }),
    })
  }
  if (!hasLists(data) && !listsEmpty(data)) {
    return jsx('div', {
      className: 'px-3.5 pb-2',
      children: jsx(Muted, { children: 'no pulse yet — first add creates it' }),
    })
  }

  const items = openMissions(pulse)
  const revision = pulse?.revision

  const flip = async (m) => {
    const i = FLIP_CYCLE.indexOf(m.status)
    const next = FLIP_CYCLE[(i + 1) % FLIP_CYCLE.length]
    haptic('tap')
    setBusy(true)
    try {
      await patchLists(ctx, streamName, {
        op: 'upsert',
        collection: 'missions',
        id: m.id,
        record: { status: next },
        base_revision: revision,
      })
      await onMutated()
    } catch (e) {
      host.notify({ kind: 'error', message: errMsg(e) })
    } finally {
      setBusy(false)
    }
  }

  const add = async () => {
    const title = draft.trim()
    if (!title) return
    haptic('tap')
    setBusy(true)
    try {
      await patchLists(ctx, streamName, {
        op: 'upsert',
        collection: 'missions',
        record: { title, status: 'todo' },
        base_revision: revision,
      })
      setDraft('')
      await onMutated()
    } catch (e) {
      host.notify({ kind: 'error', message: errMsg(e) })
    } finally {
      setBusy(false)
    }
  }

  const reorder = async (fromId, toId) => {
    if (!fromId || !toId || fromId === toId) return
    const ids = items.map(m => m.id)
    const from = ids.indexOf(fromId)
    const to = ids.indexOf(toId)
    if (from < 0 || to < 0) return
    ids.splice(from, 1)
    ids.splice(to, 0, fromId)
    haptic('tap')
    try {
      await patchLists(ctx, streamName, {
        op: 'reorder',
        collection: 'missions',
        ids,
        base_revision: revision,
      })
      await onMutated()
    } catch (e) {
      host.notify({ kind: 'error', message: errMsg(e) })
    }
  }

  return jsxs('div', {
    className: 'px-3.5 pb-2 flex flex-col gap-1.5',
    children: [
      items.length
        ? items.map(m => {
            const blk = m.status === 'blocked' ? blockerById(pulse, m.blocker_id) : null
            const rel = (m.related || []).map(id => resourceById(pulse, id)).filter(Boolean)
            return jsxs('div', {
              key: m.id,
              className: cn(
                'flex flex-col gap-0.5 rounded-[4px] px-2 py-1.5',
                dragId === m.id && 'opacity-60'
              ),
              style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
              draggable: true,
              onDragStart: () => setDragId(m.id),
              onDragOver: (e) => {
                e.preventDefault()
              },
              onDrop: (e) => {
                e.preventDefault()
                const from = dragId
                setDragId('')
                void reorder(from, m.id)
              },
              onDragEnd: () => setDragId(''),
              children: [
                jsxs('div', {
                  className: 'flex items-center gap-1.5 text-xs min-w-0',
                  children: [
                    jsx('span', {
                      className: 'cursor-grab shrink-0 text-[10px]',
                      style: { color: 'var(--ui-text-quaternary)' },
                      children: '⋮⋮',
                    }),
                    jsx(StatusDot, { tone: statusTone(m.status) }),
                    jsx('span', { className: 'flex-1 truncate font-medium', children: m.title }),
                    isOverdue(m, today) || m.due
                      ? jsx(Muted, { children: m.due })
                      : null,
                    jsx('button', {
                      type: 'button',
                      className: 'text-[10px] shrink-0 uppercase tracking-wide',
                      style: { color: 'var(--ui-text-quaternary)' },
                      disabled: busy,
                      onClick: () => flip(m),
                      children: m.status,
                    }),
                  ],
                }),
                blk
                  ? jsx('div', {
                      className: 'pl-5 text-[10px]',
                      style: { color: 'var(--destructive)' },
                      children: `stuck · ${blk.title}`,
                    })
                  : null,
                rel.length
                  ? jsx('div', {
                      className: 'pl-5 flex gap-1.5 flex-wrap',
                      children: rel.slice(0, 3).map(r =>
                        jsx('button', {
                          key: r.id,
                          type: 'button',
                          className: 'text-[10px] underline-offset-2 hover:underline',
                          style: { color: 'var(--ui-text-quaternary)' },
                          onClick: (e) => {
                            e.stopPropagation()
                            haptic('tap')
                            const href = String(r.url || '')
                            if (/^https?:\/\//i.test(href)) {
                              try {
                                if (typeof host.open === 'function') host.open(href)
                                else window.open(href, '_blank', 'noopener')
                              } catch { /* ignore */ }
                            }
                          },
                          children: r.title,
                        })
                      ),
                    })
                  : null,
              ],
            })
          })
        : jsx(Muted, { children: 'No open missions. Add one.' }),
      jsxs('form', {
        className: 'flex gap-1.5 mt-1',
        onSubmit: (e) => {
          e.preventDefault()
          void add()
        },
        children: [
          jsx(Input, {
            value: draft,
            onChange: (e) => setDraft(e.target.value),
            placeholder: 'Add a mission…',
            className: 'h-7 text-xs',
            disabled: busy,
          }),
          jsx(Button, {
            size: 'xs',
            type: 'submit',
            disabled: busy || !draft.trim(),
            children: 'Add',
          }),
        ],
      }),
      jsxs('form', {
        className: 'flex gap-1.5',
        onSubmit: async (e) => {
          e.preventDefault()
          const text = noteLine.trim()
          if (!text) return
          haptic('tap')
          setBusy(true)
          try {
            await patchLists(ctx, streamName, { op: 'add_note', text, base_revision: revision })
            setNoteLine('')
            await onMutated()
          } catch (err) {
            host.notify({ kind: 'error', message: errMsg(err) })
          } finally {
            setBusy(false)
          }
        },
        children: [
          jsx(Input, {
            value: noteLine,
            onChange: (e) => setNoteLine(e.target.value),
            placeholder: 'Drop a note…',
            className: 'h-7 text-xs',
            disabled: busy,
          }),
          jsx(Button, {
            size: 'xs',
            type: 'submit',
            disabled: busy || !noteLine.trim(),
            children: 'Note',
          }),
        ],
      }),
    ],
  })
}


/* ──── map.js ──── */
/** @section page */









function WorkstreamPage({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const activeStream = extractStreamName(cwd)
  const [filter, setFilter] = usePersisted(ctx, STORAGE_KEYS.filter, 'all')
  const [selected, setSelected] = usePersisted(ctx, STORAGE_KEYS.selected, '')
  const [query, setQuery] = useState('')
  const qc = useQueryClient()

  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: [ID, 'list'],
    queryFn: () => ctx.rest('/list?pulse=true&check=false'),
    refetchInterval: 60_000,
    retry: 1,
  })

  const selectedName = selected || activeStream || ''

  const {
    data: detail,
    isFetching: detailFetching,
    isError: detailError,
    error: detailErr,
    refetch: refetchDetail,
  } = useQuery({
    queryKey: [ID, 'stream', selectedName || 'none'],
    queryFn: async () => {
      if (!selectedName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(selectedName)}&check=true`
      )
    },
    enabled: Boolean(selectedName),
    refetchInterval: 60_000,
    retry: 1,
  })

  useEffect(() => {
    if (activeStream && !selected) setSelected(activeStream)
  }, [activeStream]) // eslint-disable-line react-hooks/exhaustive-deps

  const streams = useMemo(() => {
    const all = Array.isArray(data?.streams) ? data.streams : []
    const q = query.trim().toLowerCase()
    let list = all
    if (filter === 'adopted') list = list.filter(s => s.adopted)
    else if (filter === 'bare') list = list.filter(s => s.health === 'bare')
    else if (filter === 'issues') {
      list = list.filter(
        s =>
          ['dirty', 'degraded', 'partial', 'stale'].includes(s.health) ||
          (s.down_url_count || 0) > 0 ||
          (s.blocker_count || 0) > 0 ||
          s.lists_ok === false
      )
    }
    if (q) {
      list = list.filter(s => {
        const hay = `${s.name} ${s.title || ''} ${s.profile || ''} ${s.focus_label || ''}`.toLowerCase()
        return hay.includes(q)
      })
    }
    return list
  }, [data, filter, query])

  const stats = data?.stats || {}

  const refreshAll = async () => {
    haptic('tap')
    await refetch()
    if (selectedName) {
      try {
        await ctx.rest(
          `/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`
        )
      } catch {
        /* ignore */
      }
      await refetchDetail()
    }
    qc.invalidateQueries({ queryKey: [ID] })
  }

  if (isLoading) {
    return jsxs('div', {
      className: 'flex h-full min-h-0 w-full',
      children: [
        jsxs('div', {
          className: 'w-72 shrink-0 border-r p-3 flex flex-col gap-2',
          style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
          children: [
            jsx(Skeleton, { className: 'h-4 w-1/2' }),
            jsx(Skeleton, { className: 'h-8 w-full' }),
            jsx(Skeleton, { className: 'h-10 w-full' }),
          ],
        }),
        jsxs('div', {
          className: 'flex-1 p-6 flex flex-col gap-3',
          children: [
            jsx(Skeleton, { className: 'h-8 w-1/3' }),
            jsx(Skeleton, { className: 'h-32 w-full' }),
          ],
        }),
      ],
    })
  }

  if (isError) {
    return jsx('div', {
      className: 'p-8 h-full flex items-center justify-center',
      children: jsx(ErrorState, {
        title: /No such API|not mounted/i.test(errMsg(error))
          ? 'Backend not installed on this dashboard'
          : /unauthenticated|Unauthorized|no_cookie/i.test(errMsg(error))
            ? 'Dashboard auth required'
            : 'Workstreams failed to load',
        description: errMsg(error),
        children: jsx(Button, {
          size: 'sm',
          variant: 'secondary',
          onClick: () => {
            haptic('tap')
            refetch()
          },
          children: isFetching ? 'Retrying…' : 'Retry',
        }),
      }),
    })
  }

  return jsxs('div', {
    className: 'flex h-full min-h-0 w-full min-w-0',
    children: [
      jsx(StreamSidebar, {
        streams,
        stats,
        count: data?.count || 0,
        filter,
        setFilter,
        query,
        setQuery,
        selectedName,
        setSelected,
        activeStream,
        isFetching,
        onRefresh: refreshAll,
        emptyTitle: filter === 'all' && !query ? 'No workstreams' : 'No matches',
        emptyDesc:
          filter === 'all' && !query
            ? data?.root || 'workstreams/ is empty'
            : `Nothing matches “${query || filter}”`,
      }),
      jsx(StreamDetail, {
        selectedName,
        detail,
        detailFetching,
        detailError,
        detailErr,
        refetchDetail,
        ctx,
        onClear: () => setSelected(''),
      }),
    ],
  })
}

function StreamSidebar({
  streams,
  stats,
  count,
  filter,
  setFilter,
  query,
  setQuery,
  selectedName,
  setSelected,
  activeStream,
  isFetching,
  onRefresh,
  emptyTitle,
  emptyDesc,
}) {
  return jsxs('aside', {
    className: 'flex h-full min-h-0 w-72 shrink-0 flex-col border-r',
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      jsxs('div', {
        className: 'shrink-0 px-3 py-2.5 flex flex-col gap-2 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsx('span', {
                className: 'text-xs font-semibold tracking-tight',
                children: 'Workstreams',
              }),
              jsx(Button, {
                size: 'xs',
                variant: 'ghost',
                onClick: onRefresh,
                children: isFetching ? '…' : '↻',
              }),
            ],
          }),
          jsxs('div', {
            className: 'flex gap-1 flex-wrap',
            children: [
              jsx(StatChip, { label: 'total', value: count }),
              jsx(StatChip, { label: 'adopted', value: stats.adopted || 0, tone: 'good' }),
              (stats.issues || 0) > 0
                ? jsx(StatChip, { label: 'issues', value: stats.issues, tone: 'bad' })
                : null,
            ],
          }),
          jsx(SegmentedControl, {
            value: filter,
            onChange: id => {
              haptic('tap')
              setFilter(id)
            },
            options: FILTERS,
            className: 'w-full',
          }),
          jsx(SearchField, {
            value: query,
            onChange: setQuery,
            placeholder: 'Filter…',
            containerClassName: 'w-full',
          }),
        ],
      }),
      jsx('div', {
        className: 'min-h-0 flex-1 overflow-y-auto overflow-x-hidden',
        children:
          streams.length === 0
            ? jsx(EmptyState, { className: 'min-h-32', title: emptyTitle, description: emptyDesc })
            : streams.map(s => {
                const isActive = s.name === activeStream
                const isSel = s.name === selectedName
                const hm = healthMeta(s.health)
                return jsxs('button', {
                  key: s.name,
                  type: 'button',
                  className: cn(
                    'w-full text-left px-3 py-2 border-b transition-colors',
                    'hover:bg-accent/10',
                    isSel && 'bg-accent/10'
                  ),
                  style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
                  onClick: () => {
                    haptic('tap')
                    setSelected(s.name)
                  },
                  children: [
                    jsxs('div', {
                      className: 'flex items-center gap-2 text-xs min-w-0',
                      children: [
                        jsx(StatusDot, { tone: isActive ? 'good' : hm.tone }),
                        jsx('span', {
                          className: cn('flex-1 truncate font-medium', isActive && 'underline decoration-dotted'),
                          children: s.title || s.name,
                        }),
                        jsx(Muted, { className: 'shrink-0', children: hm.short }),
                      ],
                    }),
                    s.focus_label
                      ? jsx('div', {
                          className: 'mt-0.5 pl-4 text-[10px] truncate',
                          style: { color: 'var(--ui-text-quaternary)' },
                          children: s.focus_label,
                        })
                      : null,
                    s.blocker_count || s.waiting_on_count
                      ? jsxs('div', {
                          className: 'mt-0.5 pl-4 flex gap-2 text-[10px]',
                          children: [
                            s.waiting_on_count
                              ? jsx('span', {
                                  style: { color: 'var(--destructive)' },
                                  children: `${s.waiting_on_count} waiting`,
                                })
                              : null,
                            s.blocker_count
                              ? jsx('span', {
                                  style: { color: 'rgb(245 158 11)' },
                                  children: `${s.blocker_count} blocker${s.blocker_count === 1 ? '' : 's'}`,
                                })
                              : null,
                          ],
                        })
                      : null,
                  ],
                })
              }),
      }),
    ],
  })
}

function StreamDetail({
  selectedName,
  detail,
  detailFetching,
  detailError,
  detailErr,
  refetchDetail,
  ctx,
  onClear,
}) {
  const [tab, setTab] = usePersisted(ctx, STORAGE_KEYS.pageTab, 'missions')
  const [busy, setBusy] = useState(false)
  const [draft, setDraft] = useState('')
  const [noteDraft, setNoteDraft] = useState('')
  const [openId, setOpenId] = useState('')

  if (!selectedName) {
    return jsx('div', {
      className: 'flex-1 min-w-0 min-h-0 flex items-center justify-center p-8',
      children: jsx(EmptyState, {
        title: 'Select a workstream',
        description: 'Pick one on the left to see the picture.',
      }),
    })
  }

  if (detailError && !detail) {
    return jsx('div', {
      className: 'flex-1 min-w-0 p-8 flex items-center justify-center',
      children: jsx(ErrorState, {
        title: 'Could not load stream',
        description: errMsg(detailErr),
        children: jsx(Button, {
          size: 'sm',
          variant: 'secondary',
          onClick: () => { haptic('tap'); refetchDetail() },
          children: 'Retry',
        }),
      }),
    })
  }

  if (!detail) {
    return jsxs('div', {
      className: 'flex-1 min-w-0 p-6 flex flex-col gap-3',
      children: [
        jsx(Skeleton, { className: 'h-8 w-48' }),
        jsx(Skeleton, { className: 'h-24 w-full' }),
      ],
    })
  }

  const pulse = pulseOf(detail)
  const hm = healthMeta(detail.health)
  const title = detail.title || titleCase(selectedName)
  const nxt = nextMission(detail)
  const invalid = listsInvalid(detail)
  const wait = waitingOn(pulse)
  const stuck = stuckOn(pulse)
  const resources = pulse?.resources || []
  const notes = pulse?.notes || []
  const timeline = (pulse?.timeline || []).slice().reverse()
  const locks = pulse?.locks || []
  const pipe = pulse?.pipeline || []
  const today = todayISO(pulse?.timezone)

  const mutate = async (op) => {
    setBusy(true)
    haptic('tap')
    try {
      await patchLists(ctx, selectedName, { ...op, base_revision: pulse?.revision })
      await refetchDetail()
    } catch (e) {
      host.notify({ kind: 'error', message: errMsg(e) })
    } finally {
      setBusy(false)
    }
  }

  const LABELS = {
    missions: 'Missions',
    blockers: 'Blockers',
    resources: 'Resources',
    health: 'Health',
    ship: 'Ship',
    pipeline: 'Pipeline',
    milestones: 'Milestones',
    'waiting-on': 'Waiting-on',
    checks: 'Checks',
    locks: 'Locks',
    notes: 'Notes',
    timeline: 'Timeline',
  }
  const earned = Array.isArray(detail.widgets) && detail.widgets.length
    ? detail.widgets
    : ['missions', 'blockers', 'resources', 'notes', 'timeline']
  const tabs = earned.map(id => ({ id, label: LABELS[id] || id }))

  const activeTab = tabs.some(t => t.id === tab) ? tab : 'missions'

  return jsxs('div', {
    className: 'flex-1 min-w-0 min-h-0 flex flex-col',
    children: [
      jsxs('header', {
        className: 'shrink-0 px-6 py-4 flex flex-col gap-3 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsxs('div', {
            className: 'flex items-start justify-between gap-4',
            children: [
              jsxs('div', {
                className: 'min-w-0 flex flex-col gap-1.5',
                children: [
                  jsxs('div', {
                    className: 'flex items-center gap-2.5 min-w-0',
                    children: [
                      jsx(StatusDot, { tone: hm.tone }),
                      jsx('h1', { className: 'text-base font-semibold truncate', children: title }),
                      jsx(HealthBadge, { health: detail.health }),
                      pulse?.mode
                        ? jsx(Badge, { variant: 'muted', size: 'xs', children: pulse.mode })
                        : null,
                      detail.profile
                        ? jsx(Badge, { variant: 'muted', size: 'xs', children: `@${detail.profile}` })
                        : null,
                    ],
                  }),
                  nxt
                    ? jsxs('div', {
                        className: 'text-xs leading-snug',
                        style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                        children: [
                          jsx('span', { style: { color: 'var(--ui-text-quaternary)' }, children: 'Next · ' }),
                          nxt.title,
                        ],
                      })
                    : detail.focus_label
                      ? jsx(Muted, { children: `Focus · ${detail.focus_label}` })
                      : null,
                  jsxs('div', {
                    className: 'flex items-center gap-3 flex-wrap',
                    children: [
                      detail.repo
                        ? jsx(Muted, { children: detail.repo.replace(/^https:\/\/github.com\//, '') })
                        : null,
                      pulse?.updated_at
                        ? jsx(Muted, { children: `lists · r${pulse.revision}` })
                        : jsx(Muted, { children: 'No pulse.json' }),
                      detail.check?.checked_at
                        ? jsx(Muted, { children: `Checked ${ago(detail.check.checked_at)}` })
                        : null,
                    ],
                  }),
                ],
              }),
              jsxs('div', {
                className: 'flex gap-1.5 shrink-0',
                children: [
                  jsx(Button, {
                    size: 'sm',
                    variant: 'secondary',
                    disabled: detailFetching,
                    onClick: async () => {
                      haptic('tap')
                      try {
                        await ctx.rest(`/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`)
                      } catch { /* */ }
                      await refetchDetail()
                    },
                    children: detailFetching ? '…' : 'Recheck',
                  }),
                  jsx(Button, { size: 'sm', variant: 'ghost', onClick: onClear, children: 'Clear' }),
                ],
              }),
            ],
          }),
          invalid
            ? jsx('div', {
                className: 'text-xs',
                style: { color: 'var(--destructive)' },
                children: `pulse.json invalid — ${detail.lists?.error || 'not overwritten'}`,
              })
            : null,
          jsx('div', {
            className: 'flex gap-1 flex-wrap',
            children: tabs.map(t =>
              jsx(Button, {
                key: t.id,
                size: 'xs',
                variant: activeTab === t.id ? 'secondary' : 'ghost',
                onClick: () => { haptic('tap'); setTab(t.id) },
                children: t.label,
              })
            ),
          }),
        ],
      }),

      jsx('div', {
        className: 'min-h-0 flex-1 overflow-y-auto p-6',
        children:
          activeTab === 'missions'
            ? jsx(MissionsPicture, {
                pulse, today, busy, draft, setDraft, openId, setOpenId, mutate, invalid,
              })
            : activeTab === 'blockers' || activeTab === 'waiting-on'
              ? jsx(BlockersPicture, { wait, stuck, mutate, busy })
              : activeTab === 'resources'
                ? jsx(ResourcesPicture, { resources })
                : activeTab === 'health'
                  ? jsx(HealthPicture, { resources })
                  : activeTab === 'ship'
                    ? jsx(ShipPicture, { resources, repo: detail.repo })
                    : activeTab === 'milestones'
                      ? jsx(MilestonesPicture, { milestones: detail.pulse?.milestones || [] })
                      : activeTab === 'pipeline'
                        ? jsx(PipelinePicture, { pipe, pulse })
                        : activeTab === 'locks'
                          ? jsx(LocksPicture, { locks })
                          : activeTab === 'checks'
                            ? jsxs('div', {
                                className: 'grid grid-cols-1 xl:grid-cols-2 gap-3',
                                children: [
                                  jsx(DetailCard, { title: 'Constitution', children: jsx(CoreChecklist, { core: detail.core }) }),
                                  jsx(DetailCard, { title: 'Checks', children: jsx(ViolationList, { check: detail.check }) }),
                                ],
                              })
                            : jsx(NotesPicture, {
                                notes, timeline, noteDraft, setNoteDraft, mutate, busy,
                              }),
      }),
    ],
  })
}

function MissionsPicture({ pulse, today, busy, draft, setDraft, openId, setOpenId, mutate, invalid }) {
  if (invalid) return jsx(Muted, { children: 'Jobs disabled — pulse.json is invalid.' })
  const items = sortedMissions(pulse)
  const open = openMissions(pulse)
  return jsxs('div', {
    className: 'flex flex-col gap-3 max-w-3xl',
    children: [
      jsxs('form', {
        className: 'flex gap-2',
        onSubmit: (e) => {
          e.preventDefault()
          const title = draft.trim()
          if (!title) return
          void mutate({ op: 'upsert', collection: 'missions', record: { title, status: 'todo' } })
          setDraft('')
        },
        children: [
          jsx(Input, {
            value: draft,
            onChange: (e) => setDraft(e.target.value),
            placeholder: 'Add a mission…',
            className: 'h-8 text-xs',
            disabled: busy,
          }),
          jsx(Button, { size: 'sm', type: 'submit', disabled: busy || !draft.trim(), children: 'Add' }),
        ],
      }),
      open.length
        ? open.map(m => jsx(MissionRow, {
            key: m.id,
            m,
            pulse,
            today,
            open: openId === m.id,
            onToggle: () => setOpenId(openId === m.id ? '' : m.id),
            mutate,
            busy,
          }))
        : jsx(Muted, { children: 'No open missions.' }),
      items.some(m => m.status === 'done' || m.status === 'cancelled')
        ? jsxs('div', {
            className: 'flex flex-col gap-1 pt-2',
            children: [
              jsx(SectionLabel, { children: 'Closed' }),
              items.filter(m => m.status === 'done' || m.status === 'cancelled').map(m =>
                jsxs('div', {
                  key: m.id,
                  className: 'flex items-center gap-2 text-xs py-1',
                  children: [
                    jsx(StatusDot, { tone: statusTone(m.status) }),
                    jsx('span', { className: 'flex-1 truncate', style: { color: 'var(--ui-text-quaternary)' }, children: m.title }),
                    jsx(Button, {
                      size: 'xs',
                      variant: 'ghost',
                      disabled: busy,
                      onClick: () => mutate({ op: 'upsert', collection: 'missions', id: m.id, record: { status: 'todo' } }),
                      children: 'reopen',
                    }),
                  ],
                })
              ),
            ],
          })
        : null,
    ],
  })
}

function MissionRow({ m, pulse, today, open, onToggle, mutate, busy }) {
  const blk = m.status === 'blocked' ? blockerById(pulse, m.blocker_id) : null
  const rel = (m.related || []).map(id => resourceById(pulse, id)).filter(Boolean)
  const [why, setWhy] = useState(m.note || '')
  useEffect(() => { setWhy(m.note || '') }, [m.note, m.id])

  return jsxs('div', {
    className: 'rounded-md border px-3 py-2 flex flex-col gap-1.5',
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      jsxs('div', {
        className: 'flex items-center gap-2 text-xs min-w-0',
        children: [
          jsx(StatusDot, { tone: statusTone(m.status) }),
          jsx('button', {
            type: 'button',
            className: 'flex-1 text-left font-medium truncate hover:opacity-80',
            onClick: onToggle,
            children: m.title,
          }),
          m.due
            ? jsx(Muted, { children: String(m.due) < today ? `overdue ${m.due}` : m.due })
            : null,
          jsx(Badge, { variant: 'muted', size: 'xs', children: m.status }),
        ],
      }),
      blk
        ? jsx('div', {
            className: 'text-[10px]',
            style: { color: 'var(--destructive)' },
            children: `stuck-on · ${blk.title}`,
          })
        : null,
      open
        ? jsxs('div', {
            className: 'flex flex-col gap-2 pt-1',
            children: [
              m.goals?.length
                ? jsx('div', {
                    className: 'flex flex-col gap-0.5',
                    children: m.goals.map((g, i) =>
                      jsx('div', {
                        key: i,
                        className: 'text-[11px]',
                        style: { color: 'var(--ui-text-secondary)' },
                        children: `· ${g}`,
                      })
                    ),
                  })
                : null,
              rel.length
                ? jsx('div', {
                    className: 'flex gap-1.5 flex-wrap',
                    children: rel.map(r =>
                      jsx(Button, {
                        key: r.id,
                        size: 'xs',
                        variant: 'ghost',
                        onClick: () => {
                          const href = String(r.url || '')
                          if (/^https?:\/\//i.test(href)) {
                            try {
                              if (typeof host.open === 'function') host.open(href)
                              else window.open(href, '_blank', 'noopener')
                            } catch { /* */ }
                          }
                        },
                        children: r.title,
                      })
                    ),
                  })
                : null,
              jsxs('div', {
                className: 'flex gap-1.5',
                children: [
                  jsx(Input, {
                    value: why,
                    onChange: (e) => setWhy(e.target.value),
                    placeholder: 'Why / note…',
                    className: 'h-7 text-xs',
                  }),
                  jsx(Button, {
                    size: 'xs',
                    variant: 'secondary',
                    disabled: busy,
                    onClick: () => mutate({
                      op: 'upsert',
                      collection: 'missions',
                      id: m.id,
                      record: { note: why },
                    }),
                    children: 'Save',
                  }),
                ],
              }),
              jsxs('div', {
                className: 'flex gap-1 flex-wrap',
                children: ['todo', 'doing', 'later', 'done', 'cancelled'].map(st =>
                  jsx(Button, {
                    key: st,
                    size: 'xs',
                    variant: m.status === st ? 'secondary' : 'ghost',
                    disabled: busy,
                    onClick: () => mutate({
                      op: 'upsert',
                      collection: 'missions',
                      id: m.id,
                      record: { status: st },
                    }),
                    children: st,
                  })
                ),
              }),
            ],
          })
        : null,
    ],
  })
}

function BlockersPicture({ wait, stuck, mutate, busy }) {
  const groups = [
    { id: 'waiting-on', label: 'Waiting-on', items: wait },
    { id: 'stuck-on', label: 'Stuck-on', items: stuck },
  ]
  return jsx('div', {
    className: 'grid grid-cols-1 xl:grid-cols-2 gap-3 items-start',
    children: groups.map(g =>
      jsx(DetailCard, {
        key: g.id,
        title: g.label,
        children: g.items.length
          ? g.items.map(b =>
              jsxs('div', {
                key: b.id,
                className: 'flex flex-col gap-1 py-1.5 border-b last:border-0 text-xs',
                style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
                children: [
                  jsxs('div', {
                    className: 'flex items-center gap-2',
                    children: [
                      jsx(StatusDot, { tone: g.id === 'waiting-on' ? 'warn' : 'bad' }),
                      jsx('span', { className: 'flex-1 font-medium', children: b.title }),
                      jsx(Button, {
                        size: 'xs',
                        variant: 'ghost',
                        disabled: busy,
                        onClick: () => mutate({
                          op: 'upsert',
                          collection: 'blockers',
                          id: b.id,
                          record: { status: 'resolved' },
                        }),
                        children: 'resolve',
                      }),
                    ],
                  }),
                  b.waiting_on ? jsx(Muted, { children: b.waiting_on }) : null,
                  b.note ? jsx('div', { style: { color: 'var(--ui-text-secondary)' }, children: b.note }) : null,
                ],
              })
            )
          : jsx(Muted, { children: `No ${g.label.toLowerCase()}.` }),
      })
    ),
  })
}

function ResourcesPicture({ resources }) {
  if (!resources.length) {
    return jsx(Muted, { children: 'No resources on this stream.' })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1 max-w-2xl',
    children: resources.map(r =>
      jsxs('div', {
        key: r.id,
        className: 'flex items-center gap-2 py-1.5 text-xs border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsx(StatusDot, {
            tone: r.status === 'down' ? 'bad' : r.status === 'up' || r.status === 'merged' ? 'good' : 'muted',
          }),
          jsx('span', { className: 'font-medium truncate flex-1', children: r.title }),
          jsx(Muted, { children: r.kind }),
          /^https?:\/\//i.test(r.url || '')
            ? jsx(Button, {
                size: 'xs',
                variant: 'ghost',
                onClick: () => {
                  haptic('tap')
                  try {
                    if (typeof host.open === 'function') host.open(r.url)
                    else window.open(r.url, '_blank', 'noopener')
                  } catch { /* */ }
                },
                children: 'Open',
              })
            : jsx(Muted, { children: r.url || '' }),
        ],
      })
    ),
  })
}

function PipelinePicture({ pipe, pulse }) {
  const missions = sortedMissions(pulse)
  return jsxs('div', {
    className: 'flex flex-col gap-3',
    children: [
      jsx('div', {
        className: 'flex gap-1.5 flex-wrap',
        children: pipe.map((stage, i) =>
          jsxs('div', {
            key: stage,
            className: 'px-2 py-1 rounded-[4px] text-[11px]',
            style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
            children: [
              jsx('span', { style: { color: 'var(--ui-text-quaternary)' }, children: `${i + 1} ` }),
              stage,
            ],
          })
        ),
      }),
      jsx(Muted, { children: `${missions.filter(m => m.status === 'doing').length} doing · ${missions.filter(m => m.status === 'done').length} done` }),
    ],
  })
}

function LocksPicture({ locks }) {
  return jsx('div', {
    className: 'flex flex-col gap-2 max-w-2xl',
    children: locks.map(k =>
      jsxs('div', {
        key: k.id,
        className: 'text-xs flex flex-col gap-0.5 py-1.5 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsx('span', { className: 'font-medium', children: k.title }),
          k.decided ? jsx(Muted, { children: `decided ${k.decided}` }) : null,
        ],
      })
    ),
  })
}

function NotesPicture({ notes, timeline, noteDraft, setNoteDraft, mutate, busy }) {
  return jsxs('div', {
    className: 'grid grid-cols-1 xl:grid-cols-2 gap-3 items-start',
    children: [
      jsx(DetailCard, {
        title: 'Notes',
        children: jsxs('div', {
          className: 'flex flex-col gap-2',
          children: [
            jsxs('form', {
              className: 'flex gap-1.5',
              onSubmit: (e) => {
                e.preventDefault()
                const text = noteDraft.trim()
                if (!text) return
                void mutate({ op: 'add_note', text })
                setNoteDraft('')
              },
              children: [
                jsx(Input, {
                  value: noteDraft,
                  onChange: (e) => setNoteDraft(e.target.value),
                  placeholder: 'Add a note…',
                  className: 'h-7 text-xs',
                }),
                jsx(Button, { size: 'xs', type: 'submit', disabled: busy || !noteDraft.trim(), children: 'Add' }),
              ],
            }),
            notes.slice().reverse().map(n =>
              jsxs('div', {
                key: n.id,
                className: 'text-xs flex flex-col gap-0.5',
                children: [
                  jsx(Muted, { children: String(n.at || '').slice(0, 16) }),
                  jsx('span', { style: { color: 'var(--ui-text-secondary)' }, children: n.text }),
                ],
              })
            ),
          ],
        }),
      }),
      jsx(DetailCard, {
        title: 'Timeline',
        children: timeline.length
          ? timeline.slice(0, 24).map(e =>
              jsxs('div', {
                key: e.id,
                className: 'flex items-center gap-2 text-[11px] py-0.5',
                children: [
                  jsx(Muted, { className: 'shrink-0', children: String(e.at || '').slice(5, 16) }),
                  jsx('span', { children: e.kind }),
                  e.detail ? jsx(Muted, { children: e.detail }) : null,
                ],
              })
            )
          : jsx(Muted, { children: 'No events yet.' }),
      }),
    ],
  })
}


function HealthPicture({ resources }) {
  const urls = (resources || []).filter(r => r.kind === 'url')
  if (!urls.length) return jsx(Muted, { children: 'No URL resources.' })
  return jsx('div', {
    className: 'flex flex-col gap-1 max-w-2xl',
    children: urls.map(r =>
      jsxs('div', {
        key: r.id,
        className: 'flex items-center gap-2 py-1.5 text-xs border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsx(StatusDot, { tone: r.status === 'down' ? 'bad' : r.status === 'up' ? 'good' : 'muted' }),
          jsx('span', { className: 'flex-1 font-medium truncate', children: r.title }),
          jsx(Muted, { children: r.status || 'unknown' }),
          /^https?:\/\//i.test(r.url || '')
            ? jsx(Button, {
                size: 'xs',
                variant: 'ghost',
                onClick: () => {
                  haptic('tap')
                  try {
                    if (typeof host.open === 'function') host.open(r.url)
                    else window.open(r.url, '_blank', 'noopener')
                  } catch { /* */ }
                },
                children: 'Open',
              })
            : null,
        ],
      })
    ),
  })
}

function ShipPicture({ resources, repo }) {
  const prs = (resources || []).filter(r => r.kind === 'pr')
  return jsxs('div', {
    className: 'flex flex-col gap-2 max-w-2xl',
    children: [
      repo ? jsx(Muted, { children: String(repo).replace(/^https:\/\/github.com\//, '') }) : null,
      prs.length
        ? prs.map(r =>
            jsxs('div', {
              key: r.id,
              className: 'flex items-center gap-2 py-1.5 text-xs border-b',
              style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
              children: [
                jsx(StatusDot, { tone: r.status === 'merged' ? 'good' : r.status === 'closed' ? 'muted' : 'warn' }),
                jsx('span', { className: 'flex-1 font-medium truncate', children: r.title }),
                jsx(Muted, { children: r.status || 'open' }),
                /^https?:\/\//i.test(r.url || '')
                  ? jsx(Button, {
                      size: 'xs',
                      variant: 'ghost',
                      onClick: () => {
                        haptic('tap')
                        try {
                          if (typeof host.open === 'function') host.open(r.url)
                          else window.open(r.url, '_blank', 'noopener')
                        } catch { /* */ }
                      },
                      children: 'Open',
                    })
                  : null,
              ],
            })
          )
        : jsx(Muted, { children: 'No PR resources — repo is the door.' }),
    ],
  })
}

function MilestonesPicture({ milestones }) {
  if (!milestones?.length) return jsx(Muted, { children: 'No milestone table.' })
  return jsx('div', {
    className: 'flex flex-col max-w-2xl',
    children: milestones.map((m, i) =>
      jsxs('div', {
        key: m.id || i,
        className: 'flex items-center gap-2 py-1.5 text-xs border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsx(StatusDot, { tone: m.tone === 'good' ? 'good' : m.tone === 'bad' ? 'bad' : 'muted' }),
          jsx('span', { className: 'font-medium shrink-0', children: m.short_id || m.id }),
          jsx('span', { className: 'truncate flex-1', children: m.label || m.status || '' }),
          m.pct != null ? jsx(Muted, { children: `${m.pct}%` }) : null,
        ],
      })
    ),
  })
}

const WorkstreamMap = WorkstreamPage


/* ──── plugin.entry.js ──── */
/** @section entry */






async function runCheckNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.notify({ kind: 'info', message: 'Not inside a workstream — opening page' })
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(
      `/check?stream=${encodeURIComponent(name)}&force=true`
    )
    const n = r.violation_count || 0
    host.notify({
      kind: n ? 'error' : 'success',
      message: n
        ? `${name}: ${n} violation${n === 1 ? '' : 's'}`
        : `${name}: ${r.summary_line || 'clean'}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

async function runPulseNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(`/pulse?stream=${encodeURIComponent(name)}`)
    const lists = r.lists
    if (lists?.ok && lists.view?.next_mission) {
      const n = lists.view.next_mission
      const wait = lists.view.waiting_on_count || 0
      host.notify({
        kind: wait ? 'error' : 'info',
        message: wait
          ? `${name}: ${n.title} · ${wait} waiting-on`
          : `${name}: ${n.status} · ${n.title}`,
      })
      return
    }
    const p = r.pulse
    if (!p) {
      host.notify({ kind: 'info', message: `${name}: no STATUS-LIVE.md` })
      return
    }
    const next = p.next_action || p.focus?.short_id || p.focus?.id || 'no next action'
    const down = (p.down_urls || []).map(u => u.name).join(', ')
    host.notify({
      kind: down ? 'error' : 'info',
      message: down ? `${name}: next=${next} · down=${down}` : `${name}: next=${next}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

const plugin = {
  id: ID,
  name: 'Workstreamer',
  description:
    'Workstream pulse — chip jobs + fleet page. Lists live in scope/pulse.json.',
  defaultEnabled: true,

  register(ctx) {
    const openPage = () => {
      haptic('tap')
      host.navigate('/workstream-map')
    }

    ctx.register({
      id: 'ws-status',
      area: STATUSBAR_AREAS.right,
      order: 90,
      render: () => jsx(WorkstreamChip, { ctx }),
    })

    ctx.register({
      id: 'ws-nav',
      area: SIDEBAR_NAV_AREA,
      order: 55,
      data: {
        path: '/workstream-map',
        label: 'Workstreams',
        codicon: 'symbol-structure',
      },
    })

    ctx.register({
      id: 'workstream-map-page',
      area: ROUTES_AREA,
      data: { path: '/workstream-map' },
      render: () =>
        jsx('div', {
          className: 'h-full w-full min-h-0 min-w-0',
          children: jsx(WorkstreamPage, { ctx }),
        }),
    })

    ctx.register({
      id: 'ws-check',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.check',
        action: 'workstreamer.check',
        label: 'Workstreamer: Recheck current stream',
        keywords: ['workstream', 'workstreamer', 'stream', 'check', 'constitution', 'violations', 'ws'],
        codicon: 'check',
        run: () => runCheckNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-pulse',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.pulse',
        action: 'workstreamer.pulse',
        label: 'Workstreamer: Pulse current stream',
        keywords: ['workstream', 'workstreamer', 'stream', 'pulse', 'status', 'missions', 'ws'],
        codicon: 'pulse',
        run: () => runPulseNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-map',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.map',
        action: 'workstreamer.map',
        label: 'Workstreamer: Open page',
        keywords: ['workstream', 'workstreamer', 'stream', 'map', 'fleet', 'ws', 'page'],
        codicon: 'project',
        run: openPage,
      },
    })

    ctx.register({
      id: 'ws-map-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.map',
        label: 'Workstreamer: Open page',
        default: 'mod+alt+w',
        run: openPage,
      },
    })
    ctx.register({
      id: 'ws-check-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.check',
        label: 'Workstreamer: Recheck',
        default: 'mod+alt+c',
        run: () => runCheckNotify(ctx),
      },
    })
  },
}

const __plugin_default = plugin

export default __plugin_default
