/**
 * workstreamer — Desktop UI (ASSEMBLED)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: desktop/src/*.js
 * Rebuild: node desktop/assemble.mjs
 *
 * Modules: constants, health, format, atoms, chip, map, entry
 *
 * Deploy (Mac):
 *   mkdir -p ~/.hermes/desktop-plugins/workstreamer
 *   cp desktop/plugin.js ~/.hermes/desktop-plugins/workstreamer/plugin.js
 *   ⌘K → Reload desktop plugins
 */
import {
  Badge,
  Button,
  EmptyState,
  ErrorState,
  KEYBINDS_AREA,
  PALETTE_AREA,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ROUTES_AREA,
  SIDEBAR_NAV_AREA,
  STATUSBAR_AREAS,
  SearchField,
  SegmentedControl,
  Separator,
  Skeleton,
  StatusDot,
  Tip,
  cn,
  haptic,
  host,
  useQuery,
  useQueryClient,
  useValue
} from '@hermes/plugin-sdk'
import { jsx, jsxs } from 'react/jsx-runtime'
import { useEffect, useMemo, useState } from 'react'

/* ──── constants.js ──── */
/** @section constants */
const ID = 'workstreamer'

const FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'issues', label: 'Issues' },
  { id: 'adopted', label: 'Adopted' },
  { id: 'bare', label: 'Bare' },
]

const STORAGE_KEYS = {
  filter: 'map.filter',
  selected: 'map.selected',
}


/* ──── health.js ──── */
/** @section health */
/** Map domain health → Hermes StatusDot tone (good|muted|warn|bad). */
function healthMeta(health) {
  const map = {
    clean: { tone: 'good', label: 'clean', short: 'clean', badge: 'default' },
    adopted: { tone: 'good', label: 'adopted', short: 'ok', badge: 'default' },
    active: { tone: 'warn', label: 'in motion', short: 'active', badge: 'warn' },
    degraded: { tone: 'bad', label: 'degraded', short: 'down', badge: 'destructive' },
    dirty: { tone: 'bad', label: 'dirty', short: 'dirty', badge: 'destructive' },
    stale: { tone: 'warn', label: 'stale status', short: 'stale', badge: 'warn' },
    partial: { tone: 'warn', label: 'partial', short: 'partial', badge: 'warn' },
    bare: { tone: 'muted', label: 'bare', short: 'bare', badge: 'muted' },
  }
  return map[health] || { tone: 'muted', label: health || '…', short: health || '…', badge: 'muted' }
}

function toneOf(t) {
  if (t === 'good' || t === 'clean' || t === 'adopted') return 'good'
  if (t === 'active' || t === 'partial' || t === 'warn' || t === 'stale') return 'warn'
  if (t === 'bad' || t === 'dirty' || t === 'degraded' || t === 'error') return 'bad'
  return 'muted'
}

function badgeVariantForTone(t) {
  const x = toneOf(t)
  if (x === 'good') return 'default'
  if (x === 'warn') return 'warn'
  if (x === 'bad') return 'destructive'
  return 'muted'
}


/* ──── format.js ──── */
/** @section format */
function extractStreamName(cwd) {
  if (!cwd) return null
  const m = String(cwd).match(/workstreams\/([^/]+)/)
  return m ? m[1] : null
}

function titleCase(name) {
  if (!name) return ''
  return String(name)
    .split(/[-_]/)
    .map(p => (p ? p.charAt(0).toUpperCase() + p.slice(1) : ''))
    .join(' ')
}

function isApiMissing(e) {
  const s = errMsg(e)
  return /No such API endpoint/i.test(s) || (/\/api\/plugins\/workstreamer\//i.test(s) && /404/.test(s))
}

function errMsg(e) {
  if (!e) return 'unknown error'
  let raw = ''
  if (typeof e === 'string') raw = e
  else if (e.detail && typeof e.detail === 'object') {
    raw = e.detail.error || e.detail.message || JSON.stringify(e.detail)
  } else {
    raw = e.message || e.detail || e.error || String(e)
  }

  // Electron wraps FastAPI 404 as:
  // Error invoking remote method 'hermes:api': Error: 404: {"detail":"No such API endpoint: /api/plugins/workstreamer/list"}
  if (/No such API endpoint/i.test(raw) || (/404/.test(raw) && /workstreamer/.test(raw))) {
    return 'API not mounted on this dashboard. Copy the Python plugin to the SAME Hermes host Desktop is connected to (dashboard/manifest.json + plugins.enabled + restart). plugin.js alone is only the UI.'
  }
  if (/unauthenticated|Unauthorized|no_cookie/i.test(raw)) {
    return 'Dashboard rejected the request (not logged in). Reconnect / log in to this dashboard.'
  }
  return raw
}

function ago(ts) {
  if (!ts) return ''
  const s = Math.max(0, Math.floor(Date.now() / 1000 - Number(ts)))
  if (s < 10) return 'just now'
  if (s < 60) return `${s}s ago`
  if (s < 3600) return `${Math.floor(s / 60)}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return `${Math.floor(s / 86400)}d ago`
}

function stripMd(s) {
  return String(s || '')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1')
    .replace(/[*_`#]/g, (ch, _i, str) => {
      // keep PR numbers like #29 — only strip heading hashes at start
      return ch === '#' ? ch : ''
    })
    .replace(/^\s*[-*•]+\s+/, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/** Turn a STATUS-LIVE PR bullet into { number, title, extra, url }. */
function parsePr(raw) {
  const source = String(raw || '')
  const urlMatch = source.match(/\((https?:\/\/[^)\s]+)\)/)
  const text = stripMd(source)
  const numMatch = text.match(/#(\d+)/)
  let rest = text.replace(/#\d+\b\s*/, '').trim()
  let extra = ''
  const paren = rest.match(/^(.*?)\s*\(([^)]+)\)\s*$/)
  if (paren) {
    rest = paren[1].trim()
    extra = paren[2].trim()
  }
  return {
    number: numMatch ? numMatch[1] : '',
    title: rest || text || 'PR',
    extra,
    url: urlMatch ? urlMatch[1] : '',
    raw: text,
  }
}

function hostCwd() {
  try {
    const a = host.state.cwd
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}

function hostProfile() {
  try {
    const a = host.state.profile
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}


/* ──── atoms.js ──── */
/** @section atoms */




function Muted({ children, className }) {
  return jsx('span', {
    className: cn('text-[10px] leading-tight', className),
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function SectionLabel({ children }) {
  return jsx('div', {
    className: 'text-[10px] uppercase tracking-wide font-medium',
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function ProgressBar({ pct, tone }) {
  const p = Math.max(0, Math.min(100, Number(pct) || 0))
  const t = toneOf(tone)
  const color =
    t === 'good' ? 'var(--ui-green, var(--primary))'
      : t === 'bad' ? 'var(--destructive)'
        : t === 'warn' ? 'rgb(245 158 11)'
          : 'var(--muted-foreground)'
  return jsx('div', {
    className: 'h-1 w-full rounded-full overflow-hidden',
    style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
    role: 'progressbar',
    'aria-valuenow': p,
    'aria-valuemin': 0,
    'aria-valuemax': 100,
    children: jsx('div', {
      className: 'h-full rounded-full transition-[width] duration-200 ease-out',
      style: { width: `${p}%`, background: color },
    }),
  })
}

function MilestoneRail({ chips }) {
  if (!chips?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: chips.map(c =>
      jsx(Tip, {
        key: c.id,
        label: `${c.id}${c.label ? ` · ${c.label}` : ''}${c.status ? ` — ${c.status}` : ''}`,
        children: jsxs('div', {
          className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
          style: {
            background: 'var(--ui-stroke-secondary, var(--muted))',
            color: 'var(--ui-text-secondary, var(--muted-foreground))',
          },
          children: [
            jsx(StatusDot, { tone: toneOf(c.tone) }),
            jsx('span', { className: 'font-medium', children: c.id }),
            c.pct != null
              ? jsx('span', {
                  style: { color: 'var(--ui-text-quaternary)' },
                  children: `${c.pct}%`,
                })
              : null,
          ],
        }),
      })
    ),
  })
}

function UrlPills({ urls }) {
  if (!urls?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: urls.map(u =>
      jsx(Tip, {
        key: u.name,
        label: String(u.status || u.name),
        children: jsxs('div', {
          className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px]',
          style: {
            background: 'var(--ui-stroke-secondary, var(--muted))',
            color: toneOf(u.tone) === 'bad'
              ? 'var(--destructive)'
              : 'var(--ui-text-secondary, var(--muted-foreground))',
          },
          children: [
            jsx(StatusDot, { tone: toneOf(u.tone) }),
            u.name,
          ],
        }),
      })
    ),
  })
}

function CoreChecklist({ core }) {
  if (!core) return null
  const missing = [...(core.missing || [])]
  if (!core.has_checker) missing.push('scripts/check-workstream.sh')
  if (!core.has_status) missing.push('scope/STATUS-LIVE.md')

  if (!missing.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        `Core complete · ${core.pct}%`,
      ],
    })
  }

  return jsxs('div', {
    className: 'flex flex-col gap-1',
    children: [
      jsxs('div', {
        className: 'flex items-center justify-between text-xs',
        children: [
          jsx('span', {
            style: { color: 'var(--ui-text-secondary)' },
            children: 'Constitution',
          }),
          jsx(Muted, { children: `${core.score}/${core.total}` }),
        ],
      }),
      jsx(ProgressBar, {
        pct: core.pct,
        tone: core.pct === 100 ? 'good' : 'warn',
      }),
      jsx('div', {
        className: 'flex flex-col gap-0.5 mt-0.5',
        children: missing.slice(0, 5).map(f =>
          jsxs('div', {
            key: f,
            className: 'flex items-center gap-1.5 text-[10px]',
            style: { color: 'var(--ui-text-quaternary)' },
            children: [
              jsx('span', { children: '○' }),
              f,
            ],
          })
        ),
      }),
    ],
  })
}

function BlockerList({ blockers }) {
  if (!blockers?.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [jsx(StatusDot, { tone: 'good' }), 'No blockers listed'],
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: blockers.slice(0, 6).map((b, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs leading-snug',
        children: [
          jsx('span', {
            className: 'shrink-0 mt-0.5',
            style: { color: 'var(--destructive)' },
            children: '▸',
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: b,
          }),
        ],
      })
    ),
  })
}

function PrList({ prs, compact = false, limit = 6 }) {
  if (!prs?.length) return null
  const items = prs.slice(0, limit).map(parsePr)
  return jsx('div', {
    className: 'flex flex-col',
    children: items.map((pr, i) =>
      jsxs('div', {
        key: `${pr.number || pr.title}-${i}`,
        className: cn(
          'flex items-start gap-2 text-xs',
          compact ? 'py-0.5' : 'py-1.5',
          i > 0 && !compact ? 'border-t' : ''
        ),
        style: i > 0 && !compact
          ? { borderColor: 'var(--ui-stroke-secondary, var(--border))' }
          : undefined,
        children: [
          pr.number
            ? jsx(Badge, {
                variant: 'muted',
                size: 'xs',
                className: 'shrink-0 font-mono tabular-nums',
                children: `#${pr.number}`,
              })
            : jsx(StatusDot, { tone: 'muted' }),
          jsxs('div', {
            className: 'min-w-0 flex-1 flex flex-col gap-0.5',
            children: [
              jsx('span', {
                className: compact ? 'truncate' : 'leading-snug',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: pr.title,
              }),
              pr.extra
                ? jsx(Muted, { children: pr.extra })
                : null,
            ],
          }),
        ],
      })
    ),
  })
}

function ViolationList({ check }) {
  if (!check) return null
  if (check.status === 'no_script') {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: 'No check-workstream.sh — adopt or add scripts/',
    })
  }
  if (check.status === 'clean') {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        check.summary_line || 'Clean — no violations',
      ],
    })
  }
  const items = [
    ...(check.violations || []).map(v => ({ ...v, kind: 'v' })),
    ...(check.warnings || []).map(v => ({ ...v, kind: 'w' })),
  ]
  if (!items.length) {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: check.summary_line || check.status,
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: items.slice(0, 8).map((it, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs',
        children: [
          jsx('span', {
            className: 'font-mono text-[10px] shrink-0',
            style: {
              color: it.kind === 'v' ? 'var(--destructive)' : 'rgb(245 158 11)',
            },
            children: it.rule || (it.kind === 'v' ? 'R?' : 'W'),
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: it.message,
          }),
        ],
      })
    ),
  })
}

function StatChip({ label, value, tone }) {
  return jsxs('div', {
    className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
    style: {
      background: 'var(--ui-stroke-secondary, var(--muted))',
      color: 'var(--ui-text-secondary, var(--muted-foreground))',
    },
    children: [
      tone ? jsx(StatusDot, { tone: toneOf(tone) }) : null,
      jsx('span', { className: 'font-semibold', children: value }),
      jsx('span', {
        style: { color: 'var(--ui-text-quaternary)' },
        children: label,
      }),
    ],
  })
}

function HealthBadge({ health }) {
  const hm = healthMeta(health)
  return jsx(Badge, {
    variant: hm.badge,
    size: 'xs',
    children: hm.label,
  })
}

function RecheckButton({ onClick, busy, size = 'sm' }) {
  return jsx(Button, {
    size,
    variant: 'secondary',
    disabled: busy,
    onClick,
    children: busy ? '…' : 'Recheck',
  })
}

function DetailCard({ title, children, className }) {
  return jsxs('section', {
    className: cn(
      'rounded-md border p-3 flex flex-col gap-2 min-w-0',
      className
    ),
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      title ? jsx(SectionLabel, { children: title }) : null,
      children,
    ],
  })
}


/* ──── chip.js ──── */
/** @section chip */







function chipLabel(streamName, data, isFetching) {
  if (!data) return isFetching ? `${streamName} · …` : `${streamName} · …`
  const hm = healthMeta(data.health)
  const down = data.down_url_count || 0
  const viol = data.check?.violation_count || 0
  if (data.check?.status === 'dirty' && viol) return `${streamName} · ${viol} viol`
  if (down > 0) return `${streamName} · ${down} down`
  if (data.stale) return `${streamName} · stale`
  if (data.focus_label && ['degraded', 'active', 'dirty', 'stale'].includes(data.health)) {
    return `${streamName} · ${data.focus_label}`
  }
  return `${streamName} · ${hm.short}`
}

function WorkstreamChip({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const profile = useValue(host.state.profile)
  const streamFromCwd = extractStreamName(cwd)
  const [open, setOpen] = useState(false)
  const qc = useQueryClient()

  const { data: resolved } = useQuery({
    queryKey: [ID, 'resolve', streamFromCwd || '', profile || ''],
    queryFn: async () => {
      if (streamFromCwd) return { stream: streamFromCwd, source: 'cwd' }
      const q = new URLSearchParams()
      if (profile) q.set('profile', String(profile))
      if (cwd) q.set('cwd', String(cwd))
      return ctx.rest(`/resolve?${q}`)
    },
    refetchInterval: 30_000,
    retry: 1,
  })

  const streamName = resolved?.stream || streamFromCwd

  const { data, isFetching, isError, error, refetch } = useQuery({
    queryKey: [ID, 'stream', streamName || 'none'],
    queryFn: async () => {
      if (!streamName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(streamName)}&check=true`
      )
    },
    enabled: Boolean(streamName),
    refetchInterval: 45_000,
    retry: 1,
  })

  if (!streamName) {
    return jsx(Tip, {
      label: 'No workstream in cwd — open page',
      children: jsxs('button', {
        type: 'button',
        className:
          'inline-flex h-full items-center gap-1 rounded-none px-1.5 text-[0.6875rem] transition-colors',
        style: { color: 'var(--ui-text-quaternary)' },
        onClick: () => {
          haptic('tap')
          host.navigate('/workstream-map')
        },
        children: [
          jsx(StatusDot, { tone: 'muted' }),
          'no stream',
        ],
      }),
    })
  }

  const hm = healthMeta(data?.health)
  const label = chipLabel(streamName, data, isFetching)
  const tipBits = [
    data?.title || titleCase(streamName),
    data?.pulse?.next_action ? `Next: ${data.pulse.next_action}` : data?.focus_label,
    data?.check?.summary_line,
    isError ? `Error: ${errMsg(error)}` : null,
  ].filter(Boolean)

  return jsx(Popover, {
    open,
    onOpenChange: setOpen,
    children: [
      jsx(PopoverTrigger, {
        key: 'trigger',
        children: jsxs('button', {
          type: 'button',
          title: tipBits.join(' · ') || streamName,
          className: cn(
            'inline-flex h-full max-w-[240px] items-center gap-1.5 rounded-none px-1.5',
            'text-[0.6875rem] tabular-nums transition-colors',
            'hover:bg-(--chrome-action-hover)'
          ),
          style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
          children: [
            jsx(StatusDot, { tone: isError ? 'bad' : hm.tone }),
            jsx('span', { className: 'truncate', children: label }),
            isFetching
              ? jsx('span', {
                  className: 'text-[9px] opacity-60',
                  children: '…',
                })
              : null,
          ],
        }),
      }),
      jsx(PopoverContent, {
        key: 'content',
        className: 'w-80 p-0',
        align: 'end',
        children: jsx(StreamPopover, {
          streamName,
          data,
          profile,
          isError,
          error,
          isFetching,
          onClose: () => setOpen(false),
          onRefresh: async () => {
            haptic('tap')
            try {
              await ctx.rest(
                `/stream?stream=${encodeURIComponent(streamName)}&check=true&force=true`
              )
            } catch {
              /* refetch below surfaces error */
            }
            await refetch()
            qc.invalidateQueries({ queryKey: [ID, 'list'] })
          },
        }),
      }),
    ],
  })
}

function StreamPopover({
  streamName,
  data,
  profile,
  isError,
  error,
  isFetching,
  onClose,
  onRefresh,
}) {
  const pulse = data?.pulse
  const check = data?.check
  const core = data?.core
  const hm = healthMeta(data?.health)
  const title = data?.title || titleCase(streamName)

  if (isError && !data) {
    return jsxs('div', {
      className: 'p-3 flex flex-col gap-2',
      children: [
        jsx('div', {
          className: 'text-xs font-semibold',
          style: { color: 'var(--destructive)' },
          children: 'Failed to load stream',
        }),
        jsx('div', {
          className: 'text-xs break-words',
          style: { color: 'var(--ui-text-secondary)' },
          children: errMsg(error),
        }),
        jsxs('div', {
          className: 'flex gap-1.5',
          children: [
            jsx(Button, {
              size: 'sm',
              variant: 'secondary',
              onClick: onRefresh,
              children: 'Retry',
            }),
            jsx(Button, {
              size: 'sm',
              variant: 'ghost',
              onClick: onClose,
              children: 'Close',
            }),
          ],
        }),
      ],
    })
  }

  return jsxs('div', {
    className: 'flex flex-col',
    children: [
      jsxs('div', {
        className: 'px-3 pt-3 pb-2 flex flex-col gap-1',
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsxs('div', {
                className: 'flex items-center gap-2 min-w-0',
                children: [
                  jsx(StatusDot, { tone: hm.tone }),
                  jsx('span', {
                    className: 'font-semibold text-sm truncate',
                    children: title,
                  }),
                ],
              }),
              jsxs('div', {
                className: 'flex items-center gap-1 shrink-0',
                children: [
                  data?.profile
                    ? jsx(Badge, {
                        variant: 'muted',
                        size: 'xs',
                        children: `@${data.profile}`,
                      })
                    : null,
                  jsx(HealthBadge, { health: data?.health }),
                ],
              }),
            ],
          }),
          pulse?.next_action
            ? jsxs('div', {
                className: 'text-xs leading-snug',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: [
                  jsx('span', {
                    style: { color: 'var(--ui-text-quaternary)' },
                    children: 'Next · ',
                  }),
                  pulse.next_action,
                ],
              })
            : data?.focus_label
              ? jsx(Muted, { children: `Focus · ${data.focus_label}` })
              : null,
          jsxs('div', {
            className: 'flex items-center gap-2 flex-wrap',
            children: [
              pulse?.updated
                ? jsx(Muted, {
                    children: `STATUS-LIVE · ${pulse.updated}${pulse.stale ? ' · STALE' : ''}`,
                  })
                : null,
              check?.checked_at
                ? jsx(Muted, { children: `Checked ${ago(check.checked_at)}` })
                : null,
              data?.overall_pct != null
                ? jsx(Muted, { children: `${data.overall_pct}% overall` })
                : null,
            ],
          }),
        ],
      }),

      jsx(Separator, {}),

      pulse?.milestone_chips?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1.5',
            children: [
              jsx(SectionLabel, { children: 'Milestones' }),
              jsx(MilestoneRail, { chips: pulse.milestone_chips }),
            ],
          })
        : null,

      pulse?.urls?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1.5',
            children: [
              jsx(SectionLabel, { children: 'Live URLs' }),
              jsx(UrlPills, { urls: pulse.urls }),
            ],
          })
        : null,

      jsxs('div', {
        className: 'px-3 py-2 flex flex-col gap-1.5',
        children: [
          jsx(SectionLabel, { children: 'Blockers' }),
          jsx(BlockerList, { blockers: pulse?.blockers }),
        ],
      }),

      pulse?.prs?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1.5',
            children: [
              jsx(SectionLabel, { children: 'Open PRs' }),
              jsx(PrList, { prs: pulse.prs, compact: true, limit: 5 }),
            ],
          })
        : null,

      jsx(Separator, {}),

      jsxs('div', {
        className: 'px-3 py-2 flex flex-col gap-2',
        children: [
          jsx(SectionLabel, { children: 'Constitution' }),
          jsx(CoreChecklist, { core }),
          jsx(ViolationList, { check }),
        ],
      }),

      jsx(Separator, {}),

      jsxs('div', {
        className: 'flex gap-1.5 p-2',
        children: [
          jsx(Button, {
            size: 'sm',
            variant: 'secondary',
            className: 'flex-1',
            disabled: isFetching,
            onClick: onRefresh,
            children: isFetching ? '…' : 'Recheck',
          }),
          jsx(Button, {
            size: 'sm',
            variant: 'secondary',
            className: 'flex-1',
            onClick: () => {
              haptic('tap')
              onClose()
              host.navigate('/workstream-map')
            },
            children: 'Open page',
          }),
          jsx(Button, {
            size: 'sm',
            variant: 'ghost',
            onClick: () => {
              haptic('tap')
              onClose()
            },
            children: '✕',
          }),
        ],
      }),
    ],
  })
}


/* ──── map.js ──── */
/** @section page */







function usePersisted(ctx, key, fallback) {
  const [value, setValue] = useState(fallback)
  const [ready, setReady] = useState(false)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const v = await ctx.storage.get(key)
        if (!cancelled && v != null && v !== '') setValue(v)
      } catch {
        /* ignore */
      } finally {
        if (!cancelled) setReady(true)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [ctx, key])

  const set = (next) => {
    setValue(next)
    try {
      void ctx.storage.set(key, next)
    } catch {
      /* ignore */
    }
  }

  return [value, set, ready]
}

function WorkstreamPage({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const activeStream = extractStreamName(cwd)
  const [filter, setFilter] = usePersisted(ctx, STORAGE_KEYS.filter, 'all')
  const [selected, setSelected] = usePersisted(ctx, STORAGE_KEYS.selected, '')
  const [query, setQuery] = useState('')
  const qc = useQueryClient()

  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: [ID, 'list'],
    queryFn: () => ctx.rest('/list?pulse=true&check=false'),
    refetchInterval: 60_000,
    retry: 1,
  })

  const selectedName = selected || activeStream || ''

  const {
    data: detail,
    isFetching: detailFetching,
    isError: detailError,
    error: detailErr,
    refetch: refetchDetail,
  } = useQuery({
    queryKey: [ID, 'stream', selectedName || 'none'],
    queryFn: async () => {
      if (!selectedName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(selectedName)}&check=true`
      )
    },
    enabled: Boolean(selectedName),
    refetchInterval: 60_000,
    retry: 1,
  })

  useEffect(() => {
    if (activeStream && !selected) setSelected(activeStream)
  }, [activeStream]) // eslint-disable-line react-hooks/exhaustive-deps

  const streams = useMemo(() => {
    const all = Array.isArray(data?.streams) ? data.streams : []
    const q = query.trim().toLowerCase()
    let list = all
    if (filter === 'adopted') list = list.filter(s => s.adopted)
    else if (filter === 'bare') list = list.filter(s => s.health === 'bare')
    else if (filter === 'issues') {
      list = list.filter(
        s =>
          ['dirty', 'degraded', 'partial', 'stale'].includes(s.health) ||
          (s.down_url_count || 0) > 0 ||
          (s.blocker_count || 0) > 0
      )
    }
    if (q) {
      list = list.filter(s => {
        const hay = `${s.name} ${s.title || ''} ${s.profile || ''} ${s.focus_label || ''}`.toLowerCase()
        return hay.includes(q)
      })
    }
    return list
  }, [data, filter, query])

  const stats = data?.stats || {}

  const refreshAll = async () => {
    haptic('tap')
    await refetch()
    if (selectedName) {
      try {
        await ctx.rest(
          `/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`
        )
      } catch {
        /* ignore */
      }
      await refetchDetail()
    }
    qc.invalidateQueries({ queryKey: [ID] })
  }

  if (isLoading) {
    return jsxs('div', {
      className: 'flex h-full min-h-0 w-full',
      children: [
        jsxs('div', {
          className: 'w-64 shrink-0 border-r p-3 flex flex-col gap-2',
          style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
          children: [
            jsx(Skeleton, { className: 'h-4 w-1/2' }),
            jsx(Skeleton, { className: 'h-8 w-full' }),
            jsx(Skeleton, { className: 'h-10 w-full' }),
            jsx(Skeleton, { className: 'h-10 w-full' }),
          ],
        }),
        jsxs('div', {
          className: 'flex-1 p-6 flex flex-col gap-3',
          children: [
            jsx(Skeleton, { className: 'h-8 w-1/3' }),
            jsx(Skeleton, { className: 'h-32 w-full' }),
            jsx(Skeleton, { className: 'h-32 w-full' }),
          ],
        }),
      ],
    })
  }

  if (isError) {
    return jsx('div', {
      className: 'p-8 h-full flex items-center justify-center',
      children: jsx(ErrorState, {
        title: /No such API|not mounted/i.test(errMsg(error))
          ? 'Backend not installed on this dashboard'
          : 'Workstreams failed to load',
        description: errMsg(error),
        children: jsx(Button, {
          size: 'sm',
          variant: 'secondary',
          onClick: () => {
            haptic('tap')
            refetch()
          },
          children: isFetching ? 'Retrying…' : 'Retry',
        }),
      }),
    })
  }

  return jsxs('div', {
    className: 'flex h-full min-h-0 w-full min-w-0',
    children: [
      jsx(StreamSidebar, {
        streams,
        stats,
        count: data?.count || 0,
        filter,
        setFilter,
        query,
        setQuery,
        selectedName,
        setSelected,
        activeStream,
        isFetching,
        onRefresh: refreshAll,
        emptyTitle: filter === 'all' && !query ? 'No workstreams' : 'No matches',
        emptyDesc:
          filter === 'all' && !query
            ? data?.root || 'workstreams/ is empty'
            : `Nothing matches “${query || filter}”`,
      }),
      jsx(StreamDetail, {
        selectedName,
        detail,
        detailFetching,
        detailError,
        detailErr,
        refetchDetail,
        ctx,
        onClear: () => setSelected(''),
      }),
    ],
  })
}

function StreamSidebar({
  streams,
  stats,
  count,
  filter,
  setFilter,
  query,
  setQuery,
  selectedName,
  setSelected,
  activeStream,
  isFetching,
  onRefresh,
  emptyTitle,
  emptyDesc,
}) {
  return jsxs('aside', {
    className: 'flex h-full min-h-0 w-64 shrink-0 flex-col border-r',
    style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
    children: [
      jsxs('div', {
        className: 'shrink-0 px-3 py-2.5 flex flex-col gap-2 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsx('span', {
                className: 'text-xs font-semibold tracking-tight',
                children: 'Workstreams',
              }),
              jsx(Button, {
                size: 'xs',
                variant: 'ghost',
                onClick: onRefresh,
                children: isFetching ? '…' : '↻',
              }),
            ],
          }),
          jsxs('div', {
            className: 'flex gap-1 flex-wrap',
            children: [
              jsx(StatChip, { label: 'total', value: count }),
              jsx(StatChip, {
                label: 'adopted',
                value: stats.adopted || 0,
                tone: 'good',
              }),
              jsx(StatChip, {
                label: 'bare',
                value: stats.bare || 0,
                tone: 'muted',
              }),
              (stats.issues || 0) > 0
                ? jsx(StatChip, {
                    label: 'issues',
                    value: stats.issues,
                    tone: 'bad',
                  })
                : null,
            ],
          }),
          jsx(SegmentedControl, {
            value: filter,
            onChange: id => {
              haptic('tap')
              setFilter(id)
            },
            options: FILTERS,
            className: 'w-full',
          }),
          jsx(SearchField, {
            value: query,
            onChange: setQuery,
            placeholder: 'Filter…',
            containerClassName: 'w-full',
          }),
        ],
      }),
      jsx('div', {
        className: 'min-h-0 flex-1 overflow-y-auto overflow-x-hidden',
        children:
          streams.length === 0
            ? jsx(EmptyState, {
                className: 'min-h-32',
                title: emptyTitle,
                description: emptyDesc,
              })
            : streams.map(s => {
                const isActive = s.name === activeStream
                const isSel = s.name === selectedName
                const hm = healthMeta(s.health)
                return jsxs('button', {
                  key: s.name,
                  type: 'button',
                  className: cn(
                    'w-full text-left px-3 py-2 border-b transition-colors',
                    'hover:bg-accent/10',
                    isSel && 'bg-accent/10'
                  ),
                  style: {
                    borderColor: 'var(--ui-stroke-secondary, var(--border))',
                  },
                  onClick: () => {
                    haptic('tap')
                    setSelected(s.name)
                  },
                  children: [
                    jsxs('div', {
                      className: 'flex items-center gap-2 text-xs min-w-0',
                      children: [
                        jsx(StatusDot, { tone: isActive ? 'good' : hm.tone }),
                        jsx('span', {
                          className: cn(
                            'flex-1 truncate font-medium',
                            isActive && 'underline decoration-dotted'
                          ),
                          children: s.title || s.name,
                        }),
                        jsx(Muted, { className: 'shrink-0', children: hm.short }),
                      ],
                    }),
                    s.focus_label
                      ? jsx('div', {
                          className: 'mt-0.5 pl-4 text-[10px] truncate',
                          style: { color: 'var(--ui-text-quaternary)' },
                          children: s.focus_label,
                        })
                      : s.health === 'bare'
                        ? jsx('div', {
                            className: 'mt-0.5 pl-4 text-[10px]',
                            style: { color: 'var(--ui-text-quaternary)' },
                            children: 'not adopted',
                          })
                        : null,
                    s.blocker_count || s.down_url_count
                      ? jsxs('div', {
                          className: 'mt-0.5 pl-4 flex gap-2 text-[10px]',
                          children: [
                            s.down_url_count
                              ? jsx('span', {
                                  style: { color: 'var(--destructive)' },
                                  children: `${s.down_url_count} down`,
                                })
                              : null,
                            s.blocker_count
                              ? jsx('span', {
                                  style: { color: 'rgb(245 158 11)' },
                                  children: `${s.blocker_count} blocker${s.blocker_count === 1 ? '' : 's'}`,
                                })
                              : null,
                          ],
                        })
                      : null,
                  ],
                })
              }),
      }),
    ],
  })
}

function StreamDetail({
  selectedName,
  detail,
  detailFetching,
  detailError,
  detailErr,
  refetchDetail,
  ctx,
  onClear,
}) {
  if (!selectedName) {
    return jsx('div', {
      className: 'flex-1 min-w-0 min-h-0 flex items-center justify-center p-8',
      children: jsx(EmptyState, {
        title: 'Select a workstream',
        description: 'Pick one on the left to see pulse, milestones, and constitution.',
      }),
    })
  }

  if (detailError && !detail) {
    return jsx('div', {
      className: 'flex-1 min-w-0 p-8 flex items-center justify-center',
      children: jsx(ErrorState, {
        title: 'Could not load stream',
        description: errMsg(detailErr),
        children: jsx(Button, {
          size: 'sm',
          variant: 'secondary',
          onClick: () => {
            haptic('tap')
            refetchDetail()
          },
          children: 'Retry',
        }),
      }),
    })
  }

  if (!detail) {
    return jsxs('div', {
      className: 'flex-1 min-w-0 p-6 flex flex-col gap-3',
      children: [
        jsx(Skeleton, { className: 'h-8 w-48' }),
        jsx(Skeleton, { className: 'h-24 w-full' }),
        jsx(Skeleton, { className: 'h-24 w-full' }),
      ],
    })
  }

  const pulse = detail.pulse
  const hm = healthMeta(detail.health)
  const title = detail.title || titleCase(selectedName)
  const milestones = pulse?.milestones || []
  const urls = pulse?.urls || []

  return jsxs('div', {
    className: 'flex-1 min-w-0 min-h-0 flex flex-col',
    children: [
      jsxs('header', {
        className: 'shrink-0 px-6 py-4 flex flex-col gap-3 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsxs('div', {
            className: 'flex items-start justify-between gap-4',
            children: [
              jsxs('div', {
                className: 'min-w-0 flex flex-col gap-1.5',
                children: [
                  jsxs('div', {
                    className: 'flex items-center gap-2.5 min-w-0',
                    children: [
                      jsx(StatusDot, { tone: hm.tone }),
                      jsx('h1', {
                        className: 'text-base font-semibold truncate',
                        children: title,
                      }),
                      jsx(HealthBadge, { health: detail.health }),
                      detail.profile
                        ? jsx(Badge, {
                            variant: 'muted',
                            size: 'xs',
                            children: `@${detail.profile}`,
                          })
                        : null,
                    ],
                  }),
                  pulse?.next_action
                    ? jsxs('div', {
                        className: 'text-xs leading-snug',
                        style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                        children: [
                          jsx('span', {
                            style: { color: 'var(--ui-text-quaternary)' },
                            children: 'Next · ',
                          }),
                          pulse.next_action,
                        ],
                      })
                    : detail.focus_label
                      ? jsx(Muted, { children: `Focus · ${detail.focus_label}` })
                      : null,
                  jsxs('div', {
                    className: 'flex items-center gap-3 flex-wrap',
                    children: [
                      pulse?.updated
                        ? jsx(Muted, {
                            children: `STATUS-LIVE · ${pulse.updated}${pulse.stale ? ' · STALE' : ''}`,
                          })
                        : jsx(Muted, { children: 'No STATUS-LIVE.md' }),
                      detail.check?.checked_at
                        ? jsx(Muted, { children: `Checked ${ago(detail.check.checked_at)}` })
                        : null,
                      detail.overall_pct != null
                        ? jsx(Muted, { children: `${detail.overall_pct}% overall` })
                        : null,
                    ],
                  }),
                ],
              }),
              jsxs('div', {
                className: 'flex gap-1.5 shrink-0',
                children: [
                  jsx(Button, {
                    size: 'sm',
                    variant: 'secondary',
                    disabled: detailFetching,
                    onClick: async () => {
                      haptic('tap')
                      try {
                        await ctx.rest(
                          `/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`
                        )
                      } catch {
                        /* ignore */
                      }
                      await refetchDetail()
                    },
                    children: detailFetching ? '…' : 'Recheck',
                  }),
                  jsx(Button, {
                    size: 'sm',
                    variant: 'ghost',
                    onClick: onClear,
                    children: 'Clear',
                  }),
                ],
              }),
            ],
          }),
          pulse?.overall_pct != null || detail.core
            ? jsx(ProgressBar, {
                pct: pulse?.overall_pct ?? detail.core?.pct ?? 0,
                tone:
                  detail.health === 'degraded' || detail.health === 'dirty'
                    ? 'bad'
                    : (pulse?.overall_pct ?? detail.core?.pct) === 100
                      ? 'good'
                      : 'warn',
              })
            : null,
        ],
      }),

      jsx('div', {
        className: 'min-h-0 flex-1 overflow-y-auto p-6',
        children: jsxs('div', {
          className: 'grid grid-cols-1 xl:grid-cols-2 gap-3 items-start',
          children: [
            jsx(DetailCard, {
              title: 'Milestones',
              children: milestones.length
                ? jsxs('div', {
                    className: 'flex flex-col gap-2',
                    children: [
                      jsx(MilestoneRail, { chips: pulse.milestone_chips }),
                      jsx('div', {
                        className: 'flex flex-col',
                        children: milestones.map((m, i) =>
                          jsxs('div', {
                            key: m.id || i,
                            className: cn(
                              'flex items-center gap-2 py-1.5 text-xs',
                              i > 0 && 'border-t'
                            ),
                            style: i > 0
                              ? { borderColor: 'var(--ui-stroke-secondary, var(--border))' }
                              : undefined,
                            children: [
                              jsx(StatusDot, {
                                tone: healthMeta(
                                  m.tone === 'good' ? 'clean'
                                    : m.tone === 'bad' ? 'dirty'
                                      : m.tone === 'active' ? 'active'
                                        : 'bare'
                                ).tone,
                              }),
                              jsx('span', {
                                className: 'font-medium shrink-0 tabular-nums',
                                children: m.short_id || m.id,
                              }),
                              jsx('span', {
                                className: 'truncate flex-1',
                                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                                children: m.label || m.status,
                              }),
                              m.pct != null
                                ? jsx(Muted, { className: 'shrink-0', children: `${m.pct}%` })
                                : null,
                              m.paid
                                ? jsx(Badge, { variant: 'muted', size: 'xs', children: m.paid })
                                : null,
                            ],
                          })
                        ),
                      }),
                    ],
                  })
                : jsx(Muted, { children: 'No milestone table in STATUS-LIVE' }),
            }),

            jsx(DetailCard, {
              title: 'Live URLs',
              children: urls.length
                ? jsxs('div', {
                    className: 'flex flex-col',
                    children: [
                      jsx(UrlPills, { urls }),
                      jsx('div', {
                        className: 'mt-2 flex flex-col',
                        children: urls.map((u, i) =>
                          jsxs('div', {
                            key: u.name,
                            className: cn(
                              'flex items-center justify-between gap-2 py-1.5 text-xs',
                              i > 0 && 'border-t'
                            ),
                            style: i > 0
                              ? { borderColor: 'var(--ui-stroke-secondary, var(--border))' }
                              : undefined,
                            children: [
                              jsxs('div', {
                                className: 'flex items-center gap-2 min-w-0',
                                children: [
                                  jsx(StatusDot, {
                                    tone: u.tone === 'bad' ? 'bad' : u.tone === 'good' ? 'good' : 'muted',
                                  }),
                                  jsx('span', { className: 'font-medium truncate', children: u.name }),
                                ],
                              }),
                              jsx(Muted, { children: u.status }),
                            ],
                          })
                        ),
                      }),
                    ],
                  })
                : jsx(Muted, { children: 'No live URL table' }),
            }),

            jsx(DetailCard, {
              title: 'Blockers',
              children: jsx(BlockerList, { blockers: pulse?.blockers }),
            }),

            jsx(DetailCard, {
              title: 'Open PRs',
              children: pulse?.prs?.length
                ? jsx(PrList, { prs: pulse.prs, limit: 12 })
                : jsx(Muted, { children: 'None listed' }),
            }),

            jsx(DetailCard, {
              title: 'Constitution',
              children: jsxs('div', {
                className: 'flex flex-col gap-2',
                children: [
                  jsx(CoreChecklist, { core: detail.core }),
                  jsx(ViolationList, { check: detail.check }),
                ],
              }),
            }),

            jsx(DetailCard, {
              title: 'Pulse',
              children: jsxs('div', {
                className: 'flex flex-col gap-1.5 text-xs',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: [
                  jsxs('div', {
                    className: 'flex justify-between gap-2',
                    children: [
                      jsx(Muted, { children: 'Milestones done' }),
                      jsx('span', {
                        children: `${pulse?.done_count ?? 0} / ${pulse?.milestone_count ?? 0}`,
                      }),
                    ],
                  }),
                  jsxs('div', {
                    className: 'flex justify-between gap-2',
                    children: [
                      jsx(Muted, { children: 'Down URLs' }),
                      jsx('span', {
                        style: (pulse?.down_urls || []).length
                          ? { color: 'var(--destructive)' }
                          : undefined,
                        children: (pulse?.down_urls || []).length,
                      }),
                    ],
                  }),
                  jsxs('div', {
                    className: 'flex justify-between gap-2',
                    children: [
                      jsx(Muted, { children: 'Open PRs' }),
                      jsx('span', { children: (pulse?.prs || []).length }),
                    ],
                  }),
                  jsxs('div', {
                    className: 'flex justify-between gap-2',
                    children: [
                      jsx(Muted, { children: 'Blockers' }),
                      jsx('span', { children: (pulse?.blockers || []).length }),
                    ],
                  }),
                ],
              }),
            }),
          ],
        }),
      }),
    ],
  })
}

const WorkstreamMap = WorkstreamPage


/* ──── plugin.entry.js ──── */
/** @section entry */






async function runCheckNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.notify({ kind: 'info', message: 'Not inside a workstream — opening page' })
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(
      `/check?stream=${encodeURIComponent(name)}&force=true`
    )
    const n = r.violation_count || 0
    host.notify({
      kind: n ? 'error' : 'success',
      message: n
        ? `${name}: ${n} violation${n === 1 ? '' : 's'}`
        : `${name}: ${r.summary_line || 'clean'}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

async function runPulseNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(`/pulse?stream=${encodeURIComponent(name)}`)
    const p = r.pulse
    if (!p) {
      host.notify({ kind: 'info', message: `${name}: no STATUS-LIVE.md` })
      return
    }
    const next = p.next_action || p.focus?.short_id || p.focus?.id || 'no next action'
    const down = (p.down_urls || []).map(u => u.name).join(', ')
    host.notify({
      kind: down ? 'error' : 'info',
      message: down ? `${name}: next=${next} · down=${down}` : `${name}: next=${next}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

const plugin = {
  id: ID,
  name: 'Workstreamer',
  description:
    'Workstream constitution + live STATUS pulse — status chip and fleet page.',
  defaultEnabled: true,

  register(ctx) {
    const openPage = () => {
      haptic('tap')
      host.navigate('/workstream-map')
    }

    ctx.register({
      id: 'ws-status',
      area: STATUSBAR_AREAS.right,
      order: 90,
      render: () => jsx(WorkstreamChip, { ctx }),
    })

    ctx.register({
      id: 'ws-nav',
      area: SIDEBAR_NAV_AREA,
      order: 55,
      data: {
        path: '/workstream-map',
        label: 'Workstreams',
        codicon: 'symbol-structure',
      },
    })

    // Full page only — no always-on right rail. Open via sidebar / chip / palette.
    ctx.register({
      id: 'workstream-map-page',
      area: ROUTES_AREA,
      data: { path: '/workstream-map' },
      render: () =>
        jsx('div', {
          className: 'h-full w-full min-h-0 min-w-0',
          children: jsx(WorkstreamPage, { ctx }),
        }),
    })

    ctx.register({
      id: 'ws-check',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.check',
        action: 'workstreamer.check',
        label: 'Workstreamer: Recheck current stream',
        keywords: ['workstream', 'check', 'constitution', 'violations', 'ws'],
        codicon: 'check',
        run: () => runCheckNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-pulse',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.pulse',
        action: 'workstreamer.pulse',
        label: 'Workstreamer: Pulse current stream',
        keywords: ['workstream', 'pulse', 'status', 'milestones', 'ws'],
        codicon: 'pulse',
        run: () => runPulseNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-map',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.map',
        action: 'workstreamer.map',
        label: 'Workstreamer: Open page',
        keywords: ['workstream', 'map', 'fleet', 'ws', 'page'],
        codicon: 'project',
        run: openPage,
      },
    })

    ctx.register({
      id: 'ws-map-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.map',
        label: 'Workstreamer: Open page',
        default: 'mod+alt+w',
        run: openPage,
      },
    })
    ctx.register({
      id: 'ws-check-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.check',
        label: 'Workstreamer: Recheck',
        default: 'mod+alt+c',
        run: () => runCheckNotify(ctx),
      },
    })
  },
}

const __plugin_default = plugin

export default __plugin_default
