/**
 * workstreamer — Desktop UI (ASSEMBLED)
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Source of truth: desktop/src/*.js
 * Rebuild: node desktop/assemble.mjs
 *
 * Modules: constants, health, format, atoms, chip, map, entry
 *
 * Deploy (Mac):
 *   mkdir -p ~/.hermes/desktop-plugins/workstreamer
 *   cp desktop/plugin.js ~/.hermes/desktop-plugins/workstreamer/plugin.js
 *   ⌘K → Reload desktop plugins
 */
import {
  Badge,
  Button,
  EmptyState,
  ErrorState,
  KEYBINDS_AREA,
  PALETTE_AREA,
  Popover,
  PopoverContent,
  PopoverTrigger,
  ROUTES_AREA,
  SIDEBAR_NAV_AREA,
  STATUSBAR_AREAS,
  SearchField,
  SegmentedControl,
  Separator,
  Skeleton,
  StatusDot,
  Tip,
  cn,
  haptic,
  host,
  useQuery,
  useQueryClient,
  useValue
} from '@hermes/plugin-sdk'
import { Fragment, jsx, jsxs } from 'react/jsx-runtime'
import { useEffect, useMemo, useState } from 'react'

/* ──── constants.js ──── */
/** @section constants */
const ID = 'workstreamer'

/** Match Hermes files-browser rail sizing to avoid sash snap-glitch. */
const PANE_WIDTH = '237px'
const PANE_MIN_WIDTH = '10rem'
const PANE_MAX_WIDTH = '20rem'

const FILTERS = [
  { id: 'all', label: 'All' },
  { id: 'issues', label: 'Issues' },
  { id: 'adopted', label: 'Adopted' },
  { id: 'bare', label: 'Bare' },
]

const STORAGE_KEYS = {
  filter: 'map.filter',
  selected: 'map.selected',
}


/* ──── health.js ──── */
/** @section health */
/** Map domain health → Hermes StatusDot tone (good|muted|warn|bad). */
function healthMeta(health) {
  const map = {
    clean: { tone: 'good', label: 'clean', short: 'clean', badge: 'default' },
    adopted: { tone: 'good', label: 'adopted', short: 'ok', badge: 'default' },
    active: { tone: 'warn', label: 'in motion', short: 'active', badge: 'warn' },
    degraded: { tone: 'bad', label: 'degraded', short: 'down', badge: 'destructive' },
    dirty: { tone: 'bad', label: 'dirty', short: 'dirty', badge: 'destructive' },
    stale: { tone: 'warn', label: 'stale status', short: 'stale', badge: 'warn' },
    partial: { tone: 'warn', label: 'partial', short: 'partial', badge: 'warn' },
    bare: { tone: 'muted', label: 'bare', short: 'bare', badge: 'muted' },
  }
  return map[health] || { tone: 'muted', label: health || '…', short: health || '…', badge: 'muted' }
}

function toneOf(t) {
  if (t === 'good' || t === 'clean' || t === 'adopted') return 'good'
  if (t === 'active' || t === 'partial' || t === 'warn' || t === 'stale') return 'warn'
  if (t === 'bad' || t === 'dirty' || t === 'degraded' || t === 'error') return 'bad'
  return 'muted'
}

function badgeVariantForTone(t) {
  const x = toneOf(t)
  if (x === 'good') return 'default'
  if (x === 'warn') return 'warn'
  if (x === 'bad') return 'destructive'
  return 'muted'
}


/* ──── format.js ──── */
/** @section format */
function extractStreamName(cwd) {
  if (!cwd) return null
  const m = String(cwd).match(/workstreams\/([^/]+)/)
  return m ? m[1] : null
}

function titleCase(name) {
  if (!name) return ''
  return String(name)
    .split(/[-_]/)
    .map(p => (p ? p.charAt(0).toUpperCase() + p.slice(1) : ''))
    .join(' ')
}

function errMsg(e) {
  if (!e) return 'unknown error'
  if (typeof e === 'string') return e
  if (e.detail && typeof e.detail === 'object') {
    return e.detail.error || e.detail.message || JSON.stringify(e.detail)
  }
  return e.message || e.detail || e.error || String(e)
}

function ago(ts) {
  if (!ts) return ''
  const s = Math.max(0, Math.floor(Date.now() / 1000 - Number(ts)))
  if (s < 10) return 'just now'
  if (s < 60) return `${s}s ago`
  if (s < 3600) return `${Math.floor(s / 60)}m ago`
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  return `${Math.floor(s / 86400)}d ago`
}

function hostCwd() {
  try {
    const a = host.state.cwd
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}

function hostProfile() {
  try {
    const a = host.state.profile
    return typeof a?.get === 'function' ? a.get() : a
  } catch {
    return ''
  }
}


/* ──── atoms.js ──── */
/** @section atoms */



function Muted({ children, className }) {
  return jsx('span', {
    className: cn('text-[10px] leading-tight', className),
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function SectionLabel({ children }) {
  return jsx('div', {
    className: 'text-[10px] uppercase tracking-wide font-medium',
    style: { color: 'var(--ui-text-quaternary)' },
    children,
  })
}

function ProgressBar({ pct, tone }) {
  const p = Math.max(0, Math.min(100, Number(pct) || 0))
  const t = toneOf(tone)
  const color =
    t === 'good' ? 'var(--ui-green, var(--primary))'
      : t === 'bad' ? 'var(--destructive)'
        : t === 'warn' ? 'rgb(245 158 11)'
          : 'var(--muted-foreground)'
  return jsx('div', {
    className: 'h-1 w-full rounded-full overflow-hidden',
    style: { background: 'var(--ui-stroke-secondary, var(--muted))' },
    role: 'progressbar',
    'aria-valuenow': p,
    'aria-valuemin': 0,
    'aria-valuemax': 100,
    children: jsx('div', {
      className: 'h-full rounded-full transition-[width] duration-200 ease-out',
      style: { width: `${p}%`, background: color },
    }),
  })
}

function MilestoneRail({ chips }) {
  if (!chips?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: chips.map(c =>
      jsx(Tip, {
        key: c.id,
        label: `${c.id}${c.label ? ` · ${c.label}` : ''}${c.status ? ` — ${c.status}` : ''}`,
        children: jsxs('div', {
          className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
          style: {
            background: 'var(--ui-stroke-secondary, var(--muted))',
            color: 'var(--ui-text-secondary, var(--muted-foreground))',
          },
          children: [
            jsx(StatusDot, { tone: toneOf(c.tone) }),
            jsx('span', { className: 'font-medium', children: c.id }),
            c.pct != null
              ? jsx('span', {
                  style: { color: 'var(--ui-text-quaternary)' },
                  children: `${c.pct}%`,
                })
              : null,
          ],
        }),
      })
    ),
  })
}

function UrlPills({ urls }) {
  if (!urls?.length) return null
  return jsx('div', {
    className: 'flex gap-1 flex-wrap',
    children: urls.map(u =>
      jsx(Tip, {
        key: u.name,
        label: String(u.status || u.name),
        children: jsxs('div', {
          className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px]',
          style: {
            background: 'var(--ui-stroke-secondary, var(--muted))',
            color: toneOf(u.tone) === 'bad'
              ? 'var(--destructive)'
              : 'var(--ui-text-secondary, var(--muted-foreground))',
          },
          children: [
            jsx(StatusDot, { tone: toneOf(u.tone) }),
            u.name,
          ],
        }),
      })
    ),
  })
}

function CoreChecklist({ core }) {
  if (!core) return null
  const missing = [...(core.missing || [])]
  if (!core.has_checker) missing.push('scripts/check-workstream.sh')
  if (!core.has_status) missing.push('scope/STATUS-LIVE.md')

  if (!missing.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        `Core complete · ${core.pct}%`,
      ],
    })
  }

  return jsxs('div', {
    className: 'flex flex-col gap-1',
    children: [
      jsxs('div', {
        className: 'flex items-center justify-between text-xs',
        children: [
          jsx('span', {
            style: { color: 'var(--ui-text-secondary)' },
            children: 'Constitution',
          }),
          jsx(Muted, { children: `${core.score}/${core.total}` }),
        ],
      }),
      jsx(ProgressBar, {
        pct: core.pct,
        tone: core.pct === 100 ? 'good' : 'warn',
      }),
      jsx('div', {
        className: 'flex flex-col gap-0.5 mt-0.5',
        children: missing.slice(0, 5).map(f =>
          jsxs('div', {
            key: f,
            className: 'flex items-center gap-1.5 text-[10px]',
            style: { color: 'var(--ui-text-quaternary)' },
            children: [
              jsx('span', { children: '○' }),
              f,
            ],
          })
        ),
      }),
    ],
  })
}

function BlockerList({ blockers }) {
  if (!blockers?.length) {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [jsx(StatusDot, { tone: 'good' }), 'No blockers listed'],
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: blockers.slice(0, 6).map((b, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs leading-snug',
        children: [
          jsx('span', {
            className: 'shrink-0 mt-0.5',
            style: { color: 'var(--destructive)' },
            children: '▸',
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: b,
          }),
        ],
      })
    ),
  })
}

function ViolationList({ check }) {
  if (!check) return null
  if (check.status === 'no_script') {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: 'No check-workstream.sh — adopt or add scripts/',
    })
  }
  if (check.status === 'clean') {
    return jsxs('div', {
      className: 'flex items-center gap-2 text-xs',
      style: { color: 'var(--ui-green, var(--primary))' },
      children: [
        jsx(StatusDot, { tone: 'good' }),
        check.summary_line || 'Clean — no violations',
      ],
    })
  }
  const items = [
    ...(check.violations || []).map(v => ({ ...v, kind: 'v' })),
    ...(check.warnings || []).map(v => ({ ...v, kind: 'w' })),
  ]
  if (!items.length) {
    return jsx('div', {
      className: 'text-xs',
      style: { color: 'rgb(245 158 11)' },
      children: check.summary_line || check.status,
    })
  }
  return jsx('div', {
    className: 'flex flex-col gap-1',
    children: items.slice(0, 8).map((it, i) =>
      jsxs('div', {
        key: i,
        className: 'flex gap-2 text-xs',
        children: [
          jsx('span', {
            className: 'font-mono text-[10px] shrink-0',
            style: {
              color: it.kind === 'v' ? 'var(--destructive)' : 'rgb(245 158 11)',
            },
            children: it.rule || (it.kind === 'v' ? 'R?' : 'W'),
          }),
          jsx('span', {
            style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
            children: it.message,
          }),
        ],
      })
    ),
  })
}

function StatChip({ label, value, tone }) {
  return jsxs('div', {
    className: 'flex items-center gap-1 px-1.5 py-0.5 rounded-[3px] text-[10px] tabular-nums',
    style: {
      background: 'var(--ui-stroke-secondary, var(--muted))',
      color: 'var(--ui-text-secondary, var(--muted-foreground))',
    },
    children: [
      tone ? jsx(StatusDot, { tone: toneOf(tone) }) : null,
      jsx('span', { className: 'font-semibold', children: value }),
      jsx('span', {
        style: { color: 'var(--ui-text-quaternary)' },
        children: label,
      }),
    ],
  })
}

function HealthBadge({ health }) {
  const hm = healthMeta(health)
  return jsx(Badge, {
    variant: hm.badge,
    size: 'xs',
    children: hm.label,
  })
}

function RecheckButton({ onClick, busy, size = 'sm' }) {
  return jsx(Button, {
    size,
    variant: 'secondary',
    disabled: busy,
    onClick,
    children: busy ? '…' : 'Recheck',
  })
}


/* ──── chip.js ──── */
/** @section chip */







function chipLabel(streamName, data, isFetching) {
  if (!data) return isFetching ? `${streamName} · …` : `${streamName} · …`
  const hm = healthMeta(data.health)
  const down = data.down_url_count || 0
  const viol = data.check?.violation_count || 0
  if (data.check?.status === 'dirty' && viol) return `${streamName} · ${viol} viol`
  if (down > 0) return `${streamName} · ${down} down`
  if (data.stale) return `${streamName} · stale`
  if (data.focus_label && ['degraded', 'active', 'dirty', 'stale'].includes(data.health)) {
    return `${streamName} · ${data.focus_label}`
  }
  return `${streamName} · ${hm.short}`
}

function WorkstreamChip({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const profile = useValue(host.state.profile)
  const streamFromCwd = extractStreamName(cwd)
  const [open, setOpen] = useState(false)
  const qc = useQueryClient()

  // Resolve: prefer cwd stream; if missing, ask backend via profile
  const { data: resolved } = useQuery({
    queryKey: [ID, 'resolve', streamFromCwd || '', profile || ''],
    queryFn: async () => {
      if (streamFromCwd) return { stream: streamFromCwd, source: 'cwd' }
      const q = new URLSearchParams()
      if (profile) q.set('profile', String(profile))
      if (cwd) q.set('cwd', String(cwd))
      return ctx.rest(`/resolve?${q}`)
    },
    refetchInterval: 30_000,
    retry: 1,
  })

  const streamName = resolved?.stream || streamFromCwd

  const { data, isFetching, isError, error, refetch } = useQuery({
    queryKey: [ID, 'stream', streamName || 'none'],
    queryFn: async () => {
      if (!streamName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(streamName)}&check=true`
      )
    },
    enabled: Boolean(streamName),
    refetchInterval: 45_000,
    retry: 1,
  })

  if (!streamName) {
    return jsx(Tip, {
      label: 'No workstream in cwd — open map',
      children: jsxs('button', {
        type: 'button',
        className:
          'inline-flex h-full items-center gap-1 rounded-none px-1.5 text-[0.6875rem] transition-colors',
        style: { color: 'var(--ui-text-quaternary)' },
        onClick: () => {
          haptic('tap')
          host.navigate('/workstream-map')
        },
        children: [
          jsx(StatusDot, { tone: 'muted' }),
          'no stream',
        ],
      }),
    })
  }

  const hm = healthMeta(data?.health)
  const label = chipLabel(streamName, data, isFetching)
  const tipBits = [
    data?.title || titleCase(streamName),
    data?.pulse?.next_action ? `Next: ${data.pulse.next_action}` : data?.focus_label,
    data?.check?.summary_line,
    isError ? `Error: ${errMsg(error)}` : null,
  ].filter(Boolean)

  return jsx(Popover, {
    open,
    onOpenChange: setOpen,
    children: [
      // Plain button trigger (no Tip-asChild nesting — Tip doesn't forward refs reliably).
      jsx(PopoverTrigger, {
        key: 'trigger',
        children: jsxs('button', {
          type: 'button',
          title: tipBits.join(' · ') || streamName,
          className: cn(
            'inline-flex h-full max-w-[240px] items-center gap-1.5 rounded-none px-1.5',
            'text-[0.6875rem] tabular-nums transition-colors',
            'hover:bg-(--chrome-action-hover)'
          ),
          style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
          children: [
            jsx(StatusDot, { tone: isError ? 'bad' : hm.tone }),
            jsx('span', { className: 'truncate', children: label }),
            isFetching
              ? jsx('span', {
                  className: 'text-[9px] opacity-60',
                  children: '…',
                })
              : null,
          ],
        }),
      }),
      jsx(PopoverContent, {
        key: 'content',
        className: 'w-80 p-0',
        align: 'end',
        children: jsx(StreamPopover, {
          streamName,
          data,
          profile,
          isError,
          error,
          isFetching,
          onClose: () => setOpen(false),
          onRefresh: async () => {
            haptic('tap')
            try {
              await ctx.rest(
                `/stream?stream=${encodeURIComponent(streamName)}&check=true&force=true`
              )
            } catch {
              /* refetch below surfaces error */
            }
            await refetch()
            qc.invalidateQueries({ queryKey: [ID, 'list'] })
          },
        }),
      }),
    ],
  })
}

function StreamPopover({
  streamName,
  data,
  profile,
  isError,
  error,
  isFetching,
  onClose,
  onRefresh,
}) {
  const pulse = data?.pulse
  const check = data?.check
  const core = data?.core
  const hm = healthMeta(data?.health)
  const title = data?.title || titleCase(streamName)

  if (isError && !data) {
    return jsxs('div', {
      className: 'p-3 flex flex-col gap-2',
      children: [
        jsx('div', {
          className: 'text-xs font-semibold',
          style: { color: 'var(--destructive)' },
          children: 'Failed to load stream',
        }),
        jsx('div', {
          className: 'text-xs break-words',
          style: { color: 'var(--ui-text-secondary)' },
          children: errMsg(error),
        }),
        jsxs('div', {
          className: 'flex gap-1.5',
          children: [
            jsx(Button, {
              size: 'sm',
              variant: 'secondary',
              onClick: onRefresh,
              children: 'Retry',
            }),
            jsx(Button, {
              size: 'sm',
              variant: 'ghost',
              onClick: onClose,
              children: 'Close',
            }),
          ],
        }),
      ],
    })
  }

  return jsxs('div', {
    className: 'flex flex-col',
    children: [
      // Header
      jsxs('div', {
        className: 'px-3 pt-3 pb-2 flex flex-col gap-1',
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsxs('div', {
                className: 'flex items-center gap-2 min-w-0',
                children: [
                  jsx(StatusDot, { tone: hm.tone }),
                  jsx('span', {
                    className: 'font-semibold text-sm truncate',
                    children: title,
                  }),
                ],
              }),
              jsxs('div', {
                className: 'flex items-center gap-1 shrink-0',
                children: [
                  data?.profile
                    ? jsx(Badge, {
                        variant: 'muted',
                        size: 'xs',
                        children: `@${data.profile}`,
                      })
                    : null,
                  jsx(HealthBadge, { health: data?.health }),
                ],
              }),
            ],
          }),
          pulse?.next_action
            ? jsxs('div', {
                className: 'text-xs leading-snug',
                style: { color: 'var(--ui-text-secondary, var(--muted-foreground))' },
                children: [
                  jsx('span', {
                    style: { color: 'var(--ui-text-quaternary)' },
                    children: 'Next · ',
                  }),
                  pulse.next_action,
                ],
              })
            : data?.focus_label
              ? jsx(Muted, { children: `Focus · ${data.focus_label}` })
              : null,
          jsxs('div', {
            className: 'flex items-center gap-2 flex-wrap',
            children: [
              pulse?.updated
                ? jsx(Muted, {
                    children: `STATUS-LIVE · ${pulse.updated}${pulse.stale ? ' · STALE' : ''}`,
                  })
                : null,
              check?.checked_at
                ? jsx(Muted, { children: `Checked ${ago(check.checked_at)}` })
                : null,
              data?.overall_pct != null
                ? jsx(Muted, { children: `${data.overall_pct}% overall` })
                : null,
            ],
          }),
        ],
      }),

      jsx(Separator, {}),

      pulse?.milestone_chips?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1.5',
            children: [
              jsx(SectionLabel, { children: 'Milestones' }),
              jsx(MilestoneRail, { chips: pulse.milestone_chips }),
            ],
          })
        : null,

      pulse?.urls?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1.5',
            children: [
              jsx(SectionLabel, { children: 'Live URLs' }),
              jsx(UrlPills, { urls: pulse.urls }),
            ],
          })
        : null,

      jsxs('div', {
        className: 'px-3 py-2 flex flex-col gap-1.5',
        children: [
          jsx(SectionLabel, { children: 'Blockers' }),
          jsx(BlockerList, { blockers: pulse?.blockers }),
        ],
      }),

      pulse?.prs?.length
        ? jsxs('div', {
            className: 'px-3 py-2 flex flex-col gap-1',
            children: [
              jsx(SectionLabel, { children: 'Open PRs' }),
              jsx('div', {
                className: 'flex flex-col gap-0.5',
                children: pulse.prs.slice(0, 4).map((pr, i) =>
                  jsx('div', {
                    key: i,
                    className: 'text-xs truncate',
                    style: {
                      color: 'var(--ui-text-secondary, var(--muted-foreground))',
                    },
                    children: pr,
                  })
                ),
              }),
            ],
          })
        : null,

      jsx(Separator, {}),

      jsxs('div', {
        className: 'px-3 py-2 flex flex-col gap-2',
        children: [
          jsx(SectionLabel, { children: 'Constitution' }),
          jsx(CoreChecklist, { core }),
          jsx(ViolationList, { check }),
        ],
      }),

      jsx(Separator, {}),

      jsxs('div', {
        className: 'flex gap-1.5 p-2',
        children: [
          jsx(Button, {
            size: 'sm',
            variant: 'secondary',
            className: 'flex-1',
            disabled: isFetching,
            onClick: onRefresh,
            children: isFetching ? '…' : 'Recheck',
          }),
          jsx(Button, {
            size: 'sm',
            variant: 'secondary',
            className: 'flex-1',
            onClick: () => {
              haptic('tap')
              onClose()
              host.navigate('/workstream-map')
            },
            children: 'Map',
          }),
          jsx(Button, {
            size: 'sm',
            variant: 'ghost',
            onClick: () => {
              haptic('tap')
              onClose()
            },
            children: '✕',
          }),
        ],
      }),
    ],
  })
}


/* ──── map.js ──── */
/** @section map */







function usePersisted(ctx, key, fallback) {
  const [value, setValue] = useState(fallback)
  const [ready, setReady] = useState(false)

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const v = await ctx.storage.get(key)
        if (!cancelled && v != null && v !== '') setValue(v)
      } catch {
        /* ignore */
      } finally {
        if (!cancelled) setReady(true)
      }
    })()
    return () => {
      cancelled = true
    }
  }, [ctx, key])

  const set = (next) => {
    setValue(next)
    try {
      void ctx.storage.set(key, next)
    } catch {
      /* ignore */
    }
  }

  return [value, set, ready]
}

function WorkstreamMap({ ctx }) {
  const cwd = useValue(host.state.cwd)
  const activeStream = extractStreamName(cwd)
  const [filter, setFilter] = usePersisted(ctx, STORAGE_KEYS.filter, 'all')
  const [selected, setSelected] = usePersisted(ctx, STORAGE_KEYS.selected, '')
  const [query, setQuery] = useState('')
  const qc = useQueryClient()

  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: [ID, 'list'],
    queryFn: () => ctx.rest('/list?pulse=true&check=false'),
    refetchInterval: 60_000,
    retry: 1,
  })

  const selectedName = selected || activeStream || ''

  const {
    data: detail,
    isFetching: detailFetching,
    isError: detailError,
    error: detailErr,
    refetch: refetchDetail,
  } = useQuery({
    queryKey: [ID, 'stream', selectedName || 'none'],
    queryFn: async () => {
      if (!selectedName) return null
      return ctx.rest(
        `/stream?stream=${encodeURIComponent(selectedName)}&check=true`
      )
    },
    enabled: Boolean(selectedName),
    refetchInterval: 60_000,
    retry: 1,
  })

  // Keep selection valid when active stream changes
  useEffect(() => {
    if (activeStream && !selected) setSelected(activeStream)
  }, [activeStream]) // eslint-disable-line react-hooks/exhaustive-deps

  const streams = useMemo(() => {
    const all = Array.isArray(data?.streams) ? data.streams : []
    const q = query.trim().toLowerCase()
    let list = all
    if (filter === 'adopted') list = list.filter(s => s.adopted)
    else if (filter === 'bare') list = list.filter(s => s.health === 'bare')
    else if (filter === 'issues') {
      list = list.filter(
        s =>
          ['dirty', 'degraded', 'partial', 'stale'].includes(s.health) ||
          (s.down_url_count || 0) > 0 ||
          (s.blocker_count || 0) > 0
      )
    }
    if (q) {
      list = list.filter(s => {
        const hay = `${s.name} ${s.title || ''} ${s.profile || ''} ${s.focus_label || ''}`.toLowerCase()
        return hay.includes(q)
      })
    }
    return list
  }, [data, filter, query])

  const stats = data?.stats || {}

  const refreshAll = async () => {
    haptic('tap')
    await refetch()
    if (selectedName) {
      try {
        await ctx.rest(
          `/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`
        )
      } catch {
        /* ignore */
      }
      await refetchDetail()
    }
    qc.invalidateQueries({ queryKey: [ID] })
  }

  if (isLoading) {
    return jsxs('div', {
      className: 'p-3 flex flex-col gap-2 h-full',
      children: [
        jsx(Skeleton, { className: 'h-4 w-1/3' }),
        jsx(Skeleton, { className: 'h-8 w-full' }),
        jsx(Skeleton, { className: 'h-10 w-full' }),
        jsx(Skeleton, { className: 'h-10 w-full' }),
        jsx(Skeleton, { className: 'h-10 w-full' }),
      ],
    })
  }

  if (isError) {
    return jsx('div', {
      className: 'p-4 h-full',
      children: jsx(ErrorState, {
        title: 'Map failed to load',
        description: errMsg(error),
        children: jsx(Button, {
          size: 'sm',
          variant: 'secondary',
          onClick: () => {
            haptic('tap')
            refetch()
          },
          children: isFetching ? 'Retrying…' : 'Retry',
        }),
      }),
    })
  }

  return jsxs('div', {
    // min-h-0 + overflow chain is critical for sash resize (no layout thrash)
    className: 'flex h-full min-h-0 w-full min-w-0 flex-col',
    children: [
      // Header
      jsxs('div', {
        className: 'shrink-0 px-3 py-2 flex flex-col gap-2 border-b',
        style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
        children: [
          jsxs('div', {
            className: 'flex items-center justify-between gap-2',
            children: [
              jsx('span', {
                className: 'text-xs font-semibold tracking-tight',
                children: 'Workstreams',
              }),
              jsx(Button, {
                size: 'xs',
                variant: 'ghost',
                onClick: refreshAll,
                children: isFetching ? '…' : '↻',
              }),
            ],
          }),
          jsxs('div', {
            className: 'flex gap-1.5 flex-wrap',
            children: [
              jsx(StatChip, { label: 'total', value: data?.count || 0 }),
              jsx(StatChip, {
                label: 'adopted',
                value: stats.adopted || 0,
                tone: 'good',
              }),
              jsx(StatChip, {
                label: 'bare',
                value: stats.bare || 0,
                tone: 'muted',
              }),
              (stats.issues || 0) > 0
                ? jsx(StatChip, {
                    label: 'issues',
                    value: stats.issues,
                    tone: 'bad',
                  })
                : null,
            ],
          }),
          jsx(SegmentedControl, {
            value: filter,
            onChange: id => {
              haptic('tap')
              setFilter(id)
            },
            options: FILTERS,
            className: 'w-full',
          }),
          jsx(SearchField, {
            value: query,
            onChange: setQuery,
            placeholder: 'Filter streams…',
            containerClassName: 'w-full',
          }),
        ],
      }),

      // List
      jsx('div', {
        className: 'min-h-0 flex-1 overflow-y-auto overflow-x-hidden',
        children:
          streams.length === 0
            ? jsx(EmptyState, {
                className: 'min-h-32',
                title: filter === 'all' && !query ? 'No workstreams' : 'No matches',
                description:
                  filter === 'all' && !query
                    ? data?.root || 'workstreams/ is empty'
                    : `Nothing matches “${query || filter}”`,
              })
            : streams.map(s => {
                const isActive = s.name === activeStream
                const isSel = s.name === selectedName
                const hm = healthMeta(s.health)
                return jsxs('button', {
                  key: s.name,
                  type: 'button',
                  className: cn(
                    'w-full text-left px-3 py-2 border-b transition-colors',
                    'hover:bg-accent/10',
                    isSel && 'bg-accent/10'
                  ),
                  style: {
                    borderColor: 'var(--ui-stroke-secondary, var(--border))',
                  },
                  onClick: () => {
                    haptic('tap')
                    setSelected(s.name)
                  },
                  children: [
                    jsxs('div', {
                      className: 'flex items-center gap-2 text-xs min-w-0',
                      children: [
                        jsx(StatusDot, {
                          tone: isActive ? 'good' : hm.tone,
                        }),
                        jsx('span', {
                          className: cn(
                            'flex-1 truncate font-medium',
                            isActive && 'underline decoration-dotted'
                          ),
                          children: s.title || s.name,
                        }),
                        s.profile
                          ? jsx(Muted, { children: `@${s.profile}` })
                          : null,
                        jsx(Muted, { className: 'shrink-0', children: hm.short }),
                      ],
                    }),
                    s.focus_label
                      ? jsx('div', {
                          className: 'mt-0.5 pl-4 text-[10px] truncate',
                          style: { color: 'var(--ui-text-quaternary)' },
                          children: s.focus_label,
                        })
                      : s.health === 'bare'
                        ? jsx('div', {
                            className: 'mt-0.5 pl-4 text-[10px]',
                            style: { color: 'var(--ui-text-quaternary)' },
                            children: 'no AGENTS.md — not adopted',
                          })
                        : null,
                    s.blocker_count || s.down_url_count
                      ? jsxs('div', {
                          className: 'mt-0.5 pl-4 flex gap-2 text-[10px]',
                          children: [
                            s.down_url_count
                              ? jsx('span', {
                                  style: { color: 'var(--destructive)' },
                                  children: `${s.down_url_count} down`,
                                })
                              : null,
                            s.blocker_count
                              ? jsx('span', {
                                  style: { color: 'rgb(245 158 11)' },
                                  children: `${s.blocker_count} blocker${s.blocker_count === 1 ? '' : 's'}`,
                                })
                              : null,
                          ],
                        })
                      : null,
                    s.core
                      ? jsx('div', {
                          className: 'mt-1.5 pl-4',
                          children: jsx(ProgressBar, {
                            pct: s.overall_pct ?? s.core.pct,
                            tone:
                              s.health === 'bare'
                                ? 'muted'
                                : s.health === 'degraded' || s.health === 'dirty'
                                  ? 'bad'
                                  : s.core.pct === 100
                                    ? 'good'
                                    : 'warn',
                          }),
                        })
                      : null,
                  ],
                })
              }),
      }),

      // Detail drawer
      selectedName
        ? jsxs('div', {
            className:
              'shrink-0 border-t flex flex-col max-h-[46%] min-h-[132px] min-w-0',
            style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
            children: [
              jsxs('div', {
                className: 'px-3 py-2 flex items-center justify-between gap-2',
                children: [
                  jsxs('div', {
                    className: 'flex items-center gap-2 text-xs font-semibold min-w-0',
                    children: [
                      jsx(StatusDot, {
                        tone: healthMeta(detail?.health || 'bare').tone,
                      }),
                      jsx('span', {
                        className: 'truncate',
                        children: detail?.title || titleCase(selectedName),
                      }),
                    ],
                  }),
                  jsxs('div', {
                    className: 'flex gap-1 shrink-0',
                    children: [
                      jsx(Button, {
                        size: 'xs',
                        variant: 'ghost',
                        disabled: detailFetching,
                        onClick: async () => {
                          haptic('tap')
                          try {
                            await ctx.rest(
                              `/stream?stream=${encodeURIComponent(selectedName)}&check=true&force=true`
                            )
                          } catch {
                            /* ignore */
                          }
                          await refetchDetail()
                        },
                        children: detailFetching ? '…' : 'check',
                      }),
                      jsx(Button, {
                        size: 'xs',
                        variant: 'ghost',
                        onClick: () => setSelected(''),
                        children: '✕',
                      }),
                    ],
                  }),
                ],
              }),
              jsx('div', {
                className: 'px-3 pb-3 overflow-y-auto min-h-0 flex flex-col gap-2',
                children: detailError && !detail
                  ? jsx('div', {
                      className: 'text-xs',
                      style: { color: 'var(--destructive)' },
                      children: errMsg(detailErr),
                    })
                  : !detail
                    ? jsx(Muted, {
                        children: detailFetching ? 'Loading detail…' : 'No detail',
                      })
                    : jsxs(Fragment, {
                        children: [
                          jsx(HealthBadge, { health: detail.health }),
                          detail.pulse?.next_action
                            ? jsxs('div', {
                                className: 'text-xs leading-snug',
                                style: {
                                  color:
                                    'var(--ui-text-secondary, var(--muted-foreground))',
                                },
                                children: [
                                  jsx(SectionLabel, { children: 'Next' }),
                                  jsx('div', {
                                    children: detail.pulse.next_action,
                                  }),
                                ],
                              })
                            : null,
                          detail.pulse?.milestone_chips?.length
                            ? jsx(MilestoneRail, {
                                chips: detail.pulse.milestone_chips,
                              })
                            : null,
                          detail.pulse?.urls?.length
                            ? jsx(UrlPills, { urls: detail.pulse.urls })
                            : null,
                          detail.pulse?.blockers?.length
                            ? jsx(BlockerList, {
                                blockers: detail.pulse.blockers,
                              })
                            : null,
                          jsx(CoreChecklist, { core: detail.core }),
                          jsx(ViolationList, { check: detail.check }),
                        ],
                      }),
              }),
            ],
          })
        : jsx('div', {
            className: 'shrink-0 border-t px-3 py-2',
            style: { borderColor: 'var(--ui-stroke-secondary, var(--border))' },
            children: jsx(Muted, {
              children: 'Select a stream for pulse + check detail',
            }),
          }),
    ],
  })
}


/* ──── plugin.entry.js ──── */
/** @section entry */






async function runCheckNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.notify({ kind: 'info', message: 'Not inside a workstream — opening map' })
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(
      `/check?stream=${encodeURIComponent(name)}&force=true`
    )
    const n = r.violation_count || 0
    host.notify({
      kind: n ? 'error' : 'success',
      message: n
        ? `${name}: ${n} violation${n === 1 ? '' : 's'}`
        : `${name}: ${r.summary_line || 'clean'}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

async function runPulseNotify(ctx) {
  haptic('tap')
  const name = extractStreamName(hostCwd())
  if (!name) {
    host.navigate('/workstream-map')
    return
  }
  try {
    const r = await ctx.rest(`/pulse?stream=${encodeURIComponent(name)}`)
    const p = r.pulse
    if (!p) {
      host.notify({ kind: 'info', message: `${name}: no STATUS-LIVE.md` })
      return
    }
    const next = p.next_action || p.focus?.short_id || p.focus?.id || 'no next action'
    const down = (p.down_urls || []).map(u => u.name).join(', ')
    host.notify({
      kind: down ? 'error' : 'info',
      message: down ? `${name}: next=${next} · down=${down}` : `${name}: next=${next}`,
    })
  } catch (e) {
    host.notify({ kind: 'error', message: errMsg(e) })
  }
}

const plugin = {
  id: ID,
  name: 'Workstreamer',
  description:
    'Workstream constitution + live STATUS pulse — status chip, map pane, /ws checks.',
  defaultEnabled: true,

  register(ctx) {
    const openMap = () => {
      haptic('tap')
      host.navigate('/workstream-map')
    }

    // Status chip
    ctx.register({
      id: 'ws-status',
      area: STATUSBAR_AREAS.right,
      order: 90,
      render: () => jsx(WorkstreamChip, { ctx }),
    })

    // Sidebar nav (always one click away)
    ctx.register({
      id: 'ws-nav',
      area: SIDEBAR_NAV_AREA,
      order: 55,
      data: {
        path: '/workstream-map',
        label: 'Workstreams',
        codicon: 'symbol-structure',
      },
    })

    // Right rail pane — sized like files browser (fixed track + min/max)
    // so sash drags don't snap/shrink-then-jump.
    ctx.register({
      id: 'workstream-map',
      area: 'panes',
      title: 'Workstreams',
      data: {
        placement: 'right',
        collapsible: true,
        dock: { pane: 'workspace', pos: 'right' },
        width: PANE_WIDTH,
        minWidth: PANE_MIN_WIDTH,
        maxWidth: PANE_MAX_WIDTH,
      },
      render: () => jsx(WorkstreamMap, { ctx }),
    })

    // Full page route (same component — used by nav + palette)
    ctx.register({
      id: 'workstream-map-page',
      area: ROUTES_AREA,
      data: { path: '/workstream-map' },
      render: () =>
        jsx('div', {
          className: 'h-full w-full min-h-0',
          // Constrain page width so it doesn't look like a stretched rail
          style: { maxWidth: 420, margin: '0 auto' },
          children: jsx(WorkstreamMap, { ctx }),
        }),
    })

    // Palette
    ctx.register({
      id: 'ws-check',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.check',
        action: 'workstreamer.check',
        label: 'Workstreamer: Recheck current stream',
        keywords: ['workstream', 'check', 'constitution', 'violations', 'ws'],
        codicon: 'check',
        run: () => runCheckNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-pulse',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.pulse',
        action: 'workstreamer.pulse',
        label: 'Workstreamer: Pulse current stream',
        keywords: ['workstream', 'pulse', 'status', 'milestones', 'ws'],
        codicon: 'pulse',
        run: () => runPulseNotify(ctx),
      },
    })
    ctx.register({
      id: 'ws-map',
      area: PALETTE_AREA,
      data: {
        id: 'workstreamer.map',
        action: 'workstreamer.map',
        label: 'Workstreamer: Show Map',
        keywords: ['workstream', 'map', 'fleet', 'ws'],
        codicon: 'project',
        run: openMap,
      },
    })

    // Keybinds (mod+alt namespace — free of core chords)
    ctx.register({
      id: 'ws-map-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.map',
        label: 'Workstreamer: Show Map',
        default: 'mod+alt+w',
        run: openMap,
      },
    })
    ctx.register({
      id: 'ws-check-key',
      area: KEYBINDS_AREA,
      data: {
        id: 'workstreamer.check',
        label: 'Workstreamer: Recheck',
        default: 'mod+alt+c',
        run: () => runCheckNotify(ctx),
      },
    })
  },
}

const __plugin_default = plugin

export default __plugin_default
